### ISSUE TITLE
【質問】「多くのチャンネルを開こうとしています」のメッセージについて

### ISSUE THREAD

**Issue by naka0728** [kmiya-culti/RLogin#100]
RLoginを使っていると、以下のようなウィンドウが出ることがあるのですが  
どういうケースで出るのか教えていただけないでしょうか？  
　  

![スクリーンショット 2023-01-17 13 58 39](https://user-images.githubusercontent.com/57138515/212813636-c4a32e44-373d-4498-9fbb-91c475023ba0.png)

　  
【質問の経緯】
RLoginを使ってポートフォワードを設定しております。
また複数のポートフォワードを設定し、各サーバーに接続しているのですが、  
このウィンドウが出ると接続が切断されるため質問させていただきました。  
※10個ほどポートフォワード設定をしております。  
　  
下記を参照してポートフォワードを設定しています。
https://blog.y-yuki.net/entry/2021/04/13/003000

**Comment by kmiya-culti** [comment]
リザーブのチャンネルを含めて200個目でそのメッセージを表示します。

実際にそんなに多くのチャンネルを開くことは、少ないと思いますが
ポートフォワードの設定ミスで無限ループで開いてしまう場合を想定しています。

「はい」で続行すれば以降、このメッセージは、表示しません

**Comment by naka0728** [comment]
ご回答ありがとうございます。  
  
＞＞ リザーブのチャンネルを含めて200個目でそのメッセージを表示します。  
現在、チャンネル数はどうやって確認できるか教えていただけないでしょうか？

**Comment by naka0728** [comment]
遅くなりすみません。  
解決したためクローズとさせていただきます。  
ご回答ありがとうございました。
