### ISSUE TITLE
Version 2.28.0 におけるSSHエージェント転送の不具合

### ISSUE THREAD

**Issue by 1nagawa** [kmiya-culti/RLogin#103]
踏み台サーバーからSSHエージェント転送で各サーバーに接続する運用をしていますが、Version 2.28.0 にアップデートしたところ、エージェント転送できなくなる不具合が発生しています。

> signing failed for RSA "" from agent

とメッセージが出て拒否され、踏み台から先のサーバーに接続できなくなります。
1回目のエージェント転送接続は成功するが、それをexitしてもう一度接続しようとすると上記エラーで拒否される事もあります（再現性は不明です）。

Version 2.27.7 に戻したところ上記不具合は発生しなくなり、今までと同様にエージェント転送できるようになりましたので、Version 2.28.0 に起因するトラブルではないかと思います。
ご調査いただければ幸いです。また、追加の情報が必要であればお知らせ下さい。

OS : Windows11Pro 22H2
踏み台サーバー : Raspberry Pi4 ModelB + Raspberry Pi OS
接続先サーバー : AlmaLinux8 / 9

**Comment by kmiya-culti** [comment]
色々と条件を変えながら探してみましたが、再現できませんでした
何か条件があるようです。

別件だと思いますがPAGEANTなどを使用した場合にRSAのSHA2-256/512で署名出来ないバグがありました
この問題は、2.27.7でも同じなので関係ないですね・・・

出来れば詳しく使用状況をお知らせいただけば幸いです。
うまくこちらで再現出来ればよいのですが・・・・

**Comment by 1nagawa** [comment]
お調べいただきありがとうございます。

- SSH鍵はPagentではなく、RLoginの設定画面で登録（サーバー > プロトコル > 認証キー）から登録しています（大事な情報だったかも知れません、報告で漏れていてすみません）。
- 踏み台のSSHのセッション中、1台目のサーバーはエージェント転送が成功しますが、そこをexitで抜けて2台目以降のサーバーへ接続を試みると拒否される状況です。

sshdのデバッグログをオンにして追っていますが、差分が見つけられていない状況です。いったん上記の情報までをご報告させていただきます。

**Comment by 1nagawa** [comment]
踏み台からのsshを-vvでデバッグトレースすると接続が成功するという、おかしな現象が起きてますね……。
接続先のsshdのデバッグログで怪しそうなのは、この辺でしょうか。

```
Mar 22 19:36:23 （ホスト名） sshd[27667]: debug1: /home/（ユーザー名）/.ssh/authorized_keys:1: key options: agent-forwarding port-forwarding pty user-rc x11-forwarding
Mar 22 19:36:23 （ホスト名） sshd[27667]: Accepted key RSA SHA256:*********** found at /home/（ユーザー名）/.ssh/authorized_keys:1
Mar 22 19:36:23 （ホスト名） sshd[27667]: debug1: restore_uid: 0/0
Mar 22 19:36:23 （ホスト名） sshd[27667]: debug2: userauth_pubkey: authenticated 0 pkalg rsa-sha2-512 [preauth]
Mar 22 19:36:23 （ホスト名） sshd[27667]: Postponed publickey for （ユーザー名） from 192.168.0.2 port 41412 ssh2 [preauth]
Mar 22 19:36:23 （ホスト名） sshd[27667]: Connection closed by authenticating user yushi 192.168.0.2 port 41412 [preauth]
Mar 22 19:36:23 （ホスト名） sshd[27667]: debug1: do_cleanup [preauth]
Mar 22 19:36:23 （ホスト名） sshd[27667]: debug1: monitor_read_log: child log fd closed
Mar 22 19:36:23 （ホスト名） sshd[27667]: debug1: do_cleanup
Mar 22 19:36:23 （ホスト名） sshd[27667]: debug1: PAM: cleanup
Mar 22 19:36:23 （ホスト名） sshd[27667]: debug1: Killing privsep child 27668
```

**Comment by kmiya-culti** [comment]
原因が判明しました。2.28.0でのバグです
Agenttのパケットが細かく分断された場合に結合に失敗していました。

デバッグにお付き合いいただき有り難うございました。
次回バージョンで修正したいと思います。

**Comment by 1nagawa** [comment]
Version 2.28.1 で不具合が解消したのを確認しました。
ご対応いただきありがとうございました。
