### ISSUE TITLE
2MBのファイルのSFTPアップロードが応答なしで正常に完了しない

### ISSUE THREAD

**Issue by abe-masanori** [kmiya-culti/RLogin#105]
SFTPで2MBのファイルをアップロードしようとした場合、ターミナルウィンドウ、SFTPのウィンドウの両方が「応答なし」になり、ファイルのアップロードが正常に完了しません。

- 2.28.0ではこの問題は発生していません。
- 2.28.1でも小さいサイズのファイル（数KB程度）は問題なくアップロードできています。問題が発生する境界サイズを調べてみましたが、変動するようです。1MBではこの問題が発生したりしなかったりです。
- SSHでのコマンドラインの操作には問題は発生していません。

環境依存なのかもしれませんが、報告します。

【環境】
RLogin : 2.28.1 (rlogin_x64.zip)
接続元OS : Windows 10 22H2
接続先OS：Oracle Linux 8.7（接続元OS上の仮想マシン。ブリッジ接続）

【再現手順】

1.  [Sever Select]の画面で以下のみを入力した接続エントリを作成する。

- エントリー(上)
- ホスト名(サーバーIPアドレス)
- ログインユーザー名
- パスワード

2. 上で作成したエントリで接続後、メニューから [ファイル] → [SFTPファイルの転送] を選択する。

3. 表示されたSFTPウィンドウで、左から右にファイルをドラッグ＆ドロップする。

**Comment by kmiya-culti** [comment]
ご報告有り難うございます。
タイミングによりデッドロックが発生していました。
すでに修正しています。お試しいただければ幸いです。

http://nanno.bf1.jp/softlib/rlogin/2.28.2/

**Comment by abe-masanori** [comment]
リンク先のファイル（rlogin_x64.zip）で問題なくSFTPアップロードできることを確認しました。
ありがとうございました。
