### ISSUE TITLE
ファイル転送でフリーズ(2.28.1)

### ISSUE THREAD

**Issue by osapon** [kmiya-culti/RLogin#106]
バージョン2.28.1で、SSH接続したサーバにファイル転送でダウンロード・アップロードするとフリーズしてしまいます。

2.28.0および2.27.7では問題ありませんでした。

**Comment by kmiya-culti** [comment]
sftpでのファイル転送ならばすでにissuesで報告をもらっております
https://github.com/kmiya-culti/RLogin/issues/105

修正した次期試作版でお試しいただければ幸いです
http://nanno.bf1.jp/softlib/rlogin/2.28.2/

**Comment by osapon** [comment]
すみません、close済みのissueを確認していませんでした。
