### ISSUE TITLE
SFtpファイル転送が途中で停止する

### ISSUE THREAD

**Issue by mee1080** [kmiya-culti/RLogin#107]
Version 2.28.1 にて、200MB程度のファイルを、SFtpファイル転送でローカルにコピーしようとすると、途中で停止し、応答なしとなりました。
複数のファイルで計3回試行し、すべて同じ現象が発生しました。
Version 2.28.0 で試したところ、問題なくファイル転送が完了しました。
OSはWindows 11 Homeです。その他必要な情報がありましたら、ご教示願います。

**Comment by kmiya-culti** [comment]
すでに同じ報告をいただいております
https://github.com/kmiya-culti/RLogin/issues/105
https://github.com/kmiya-culti/RLogin/issues/106

次期バージョンを上げるまでこのissuesをクローズしないでもらえれば助かります
