### ISSUE TITLE
Rloginでsftp転送ができない

### ISSUE THREAD

**Issue by suzumiya-3** [kmiya-culti/RLogin#108]
はじめまして、お世話になっております。
私は自宅でサーバーなど色々試している者です。
Culti氏のRloginはとても便利なので愛用させてもらっています。
しかし今日rtx1200でsftp転送をしようとすると、
```
Runtime Error!
Program: (実行ファイル)
R6025
  - pure virtual function call
```
と表示されてソフトが落ちてしまいます。
rtx1200を使用しているのが原因かと思われますがこれは修正できませんでしょうか?

バージョンは windowsの2.28.2であります。
ご確認お願いいたします。

**Comment by kmiya-culti** [comment]
sftpを起動出来ない場合にRuntime Errorが発生していました
エラー処理を修正しました。ご報告有り難うございました。

http://nanno.bf1.jp/softlib/rlogin/2.28.3/

**Comment by suzumiya-3** [comment]
修正ありがとうございます。
お役に立てて何よりです。

**Comment by suzumiya-3** [comment]
閉じた後で申し訳ないですが最後に確認したいです。
バージョンを2.28.3に変更しましてエラーが無くなりましたけれども接続ができないです。
> sftpを起動出来ない場合...
この文から考えるに私が使っているRTX1200は対応していない、それとも何か他に要因があるということでしょうか?

**Comment by kmiya-culti** [comment]
http://www.rtpro.yamaha.co.jp/RT/docs/sftpd/
によるとsftpに制限があるようです

**Comment by suzumiya-3** [comment]
一ヶ月越しで申し訳ないですが気になる点があったのでコメントを残させていただきます。

rtx1200でsftpを接続したあと，2.28.3で修正されたエラー処理の修正で確かに
sftpのポップアップの方は閉じました。

しかしそのあと，
```
SSH2 Receive Disconnect Message
no Channel
```
というポップアップが出たあとssh接続が閉じてしまいました。(Administratorで接続した場合も含む)

少なくとも上の検証時ではsftpによる制限は達成したと思います。
なにか解決方法はありますでしょうか?

**Comment by wataru5123** [comment]
見ていて気になるのでコメントしますが
制限を達成とはどのようなことを指しているのでしょうか
既にアプリケーション側の問題とも思えないのですが

**Comment by suzumiya-3** [comment]
こんにちは，wataru5123さん。

> 制限を達成した...

というのはrtx1200のsftpの接続に伴う制限について，その制限を達成したという意味です。
culti氏のこのコメント(https://github.com/kmiya-culti/RLogin/issues/108#issuecomment-161386690) にまつわる返信ですね。
すこし分かりづらく申し訳なかったです。

**Comment by kmiya-culti** [comment]
> SSH2 Receive Disconnect Message
> no Channel

は、サーバーから"no Channel"とエラーを返していますので
サーバー側のエラーログを参照されては、いかがでしょうか？

気になるのは・・・

>> 少なくとも上の検証時ではsftpによる制限は達成したと思います。

> というのはrtx1200のsftpの接続に伴う制限について，その制限を達成したという意味です。

とのことですが具体的内容が無いので判断のしようがないと言うことですね
RTX1200の設定をRLoginのページで期待されるのは、難しいですね・・・

http://www.rtpro.yamaha.co.jp/RT/docs/sftpd/
上記ページの「SFTPのアクセス制限」で「同時に複数のユーザーがログインすることはできません」
とあるのでsshでログインした状態では、sftpを実行できないのでは、ないでしょうか？

RLoginで出来ることとしては、オプション・プロトコル・SSHの「シェル起動なしでPFログを表示」
をチェックでしょうか・・・

**Comment by suzumiya-3** [comment]
ご返事ありがとうございます。

>「接続時にSFTPを起動」をチェック
これで接続ができました。

ユーザー名はユーザーの物を，パスワードは管理者の物を入れることで
管理者権限としてログインすることができ，ファイル等の転送やコピーが可能でした。

原因はculit氏の通り複数ユーザーでのアクセスをrtx1200側が許可していないということみたいでした。

これで本当のクローズができます。
ありがとうございました。
