### ISSUE TITLE
【機能要望】sshセッション中、一時的にポートフォワードの設定を追加・変更したい

### ISSUE THREAD

**Issue by jg-shinji-ueda** [kmiya-culti/RLogin#109]
# 前提

私は putty からの乗り換えで RLogin を採用しようとしており、
ほぼ検証は終わっています。

1点だけ、putty との操作性で異なる点があり、その点が自分の仕事の進め方とマッチしていないため、
今回Issueを起票しました。

現在のRLoginの機能や過去のIssueも一通り確認しましたが、同様の機能やIssueは見つけられませんでした。
もし、該当機能が既に存在している場合や、過去に議論されたIssueがある場合は教えください。

# RLoginでやりたい事

接続済みのSSHセッションに対して、そのセッションの接続中および再接続後の状態でのみ、
一時的にポートフォワードの設定を有効にしたい。

※ 該当セッションを閉じた場合、次回以後、保存済みの接続設定から接続しても、
    一時的に設定したポートフォワードは有効にならない。

利用シーンとしては「今だけ本番環境にポートフォワードをしたい」を想定しています。

**Comment by kmiya-culti** [comment]
次回バージョンで・・・
オプション設定のsshポートフォワードの更新を行うように変更
を予定しています。

http://nanno.bf1.jp/softlib/rlogin/2.28.3/

**Comment by jg-shinji-ueda** [comment]
@kmiya-culti 

ご返答ありがとうございます。

次回のバージョンで検討頂けているとの事、私にとっては朗報で歓喜しました。

記載頂いたリポジトリのURLを見たところ、時期バージョンのライブラリがあると思いましたので、
以下の項目でテストしてみました。

仕様がわかっていませんので何が正しいかわかりませんがご参考としてください。
※ 結果がわかりにくいと思ったので、※で私個人の所管のテスト結果を追記しました。


# case1 「その他 オプションの継承」を利用していない場合

## オプション設定でポートフォワード設定の追加
 ⇒ ポートフォワードができた  ※OK

## オプション設定で既存のポートフォワード設定を削除
 ⇒ ポートフォワードできない  ※OK

## 「接続を閉じる」 を選択
 ⇒ 設定を保存するかどうかの有無をダイアログで質問される
```
   A) 設定の変更を保存しないを選択
      ⇒ 設定情報が更新されない ※OK

   B) 設定の変更を保存するを選択
      ⇒ 設定情報が更新された ※OK
```

# case2 「その他 オプションの継承」を利用している場合

## オプション設定でポートフォワード設定の追加
 ⇒ ポートフォワードができた  ※OK

## オプション設定で既存のポートフォワード設定を削除
 ⇒ ポートフォワードできない  ※OK

## 「接続を閉じる」 を選択
 ⇒ 設定を保存するかどうかの有無をダイアログで質問される
```
   A) 設定の変更を保存しないを選択
      ⇒ 設定情報が更新されない ※OK

   B) 設定の変更を保存するを選択
     B-1) 標準/エントリーのオプション設定を使用しているエントリーです。前設定を上書きして使用を解除しますか？
          「はい」を選択
          ⇒ 「その他 オプションの継承」 のチェックボックスが外れ、ポートフォワードの設定が上書きされた。 ※？

     B-2) 標準/エントリーのオプション設定を使用しているエントリーです。前設定を上書きして使用を解除しますか？
          「いいえ」を選択
           ⇒ 接続が切れなかった。設定ファイルの変更もなかった。 ※ OK
```

「※？」 とした部分ですが、
動作結果を2度見すれば、動作は合っていると思いましたが、
初見で「前設定を上書きして使用を解除しますか？」のダイアログを見たときに、判断が難しいなぁと感じました。（個人の所見です。）


リリース、お待ちしております。今後も応援します。

**Comment by jg-shinji-ueda** [comment]
@kmiya-culti 

Thank you for release!!
🚀
