### ISSUE TITLE
rlogin最小化した状態でも/inuse起動するとタブ起動してほしい

### ISSUE THREAD

**Issue by koomae** [kmiya-culti/RLogin#11]
rloginのウインドウを最小化した状態でコマンドラインの/inuseオプションで起動すると新規Rloginウインドウを開きます。
可能であれば最小化したウインドウを開き、そのウインドウ上でタブ起動してほしいです。

**Comment by kmiya-culti** [comment]
2.20.8の時に「/inuse指定時にアイコン状態ウィンドウを無視するように変更」とした理由を思い出せませんが、「最小化したウインドウを開き、そのウインドウ上でタブ起動」の動作を考えていなかったと思います。どのような動作が便利なのでしょうねぇ・・・

**Comment by kmiya-culti** [comment]
次期バージョンに/inuseaオプションを追加して最小化したRLoginも対象にするオプションを追加してみようと思います。

http://nanno.dip.jp/softlib/rlogin/2.23.1/

**Comment by koomae** [comment]
オプションを追加していただきありがとうございます。
最小化したRLoginでもタブ起動する事を確認致しました。
