### ISSUE TITLE
windows xp上で起動ができない

### ISSUE THREAD

**Issue by suzumiya-3** [kmiya-culti/RLogin#110]
お世話になっています。#108の人です。

今回、windows xp上でRLoginを起動させようとするとエラーで起動できなかったのでissueを立てました。

rtx 1200と接続する際、手持ちのwindows xpとcomポートで、
telnet接続しようとした際、エラーが発生し起動できませんでした。

```
プロシージャ エントリ ポイント CancelIoEx がダイナミック リンク ライブラリー KERNEL32.dll 見つかりませんでした。
```

windows xpなのでいまさら使ってるのかと言われるのは承知ですが
comポートがあるpcがこれしかない故、またときどきこのpcも使おうと思っております。

なので修正にお手数お掛けするかも知れませんが、よろしくお願いします。

ちなみにOSはWindows XP, SP3です。

追記: windows xpをもし打ち切っているならこちらのほう閉じようと思っています。
また、#108の方はこれが終わったら一度確認したいと思っています。

**Comment by kmiya-culti** [comment]
ご報告有り難うございます。
次期バージョンで修正したいと思います

http://nanno.bf1.jp/softlib/rlogin/2.28.4/

**Comment by suzumiya-3** [comment]
さっそく修正ありがとうございます。
確認もできたのでこちら閉じさせていただきます。
ありがとうございました。
