### ISSUE TITLE
Tabキーを押して補完をかけると、画面が一瞬反転する

### ISSUE THREAD

**Issue by cidrugHug8** [kmiya-culti/RLogin#111]
最近？ここ2週間くらいかと思いますが、Tabキーを押して補完をかけるとRLoginの画面全体が一瞬反転するようになりました。何か設定をいじってこの動きを抑制できるなら教えていただけますでしょうか。

よろしくお願いいたします。
![通常](https://github.com/kmiya-culti/RLogin/assets/11013023/af7188b5-4208-42c1-9f60-a8192d000383)
![Tabキーを押してウィンドウ画面が反転したときのキャプチャ](https://github.com/kmiya-culti/RLogin/assets/11013023/a1cb297c-961e-422c-9bbd-f64c5380ecc1)

**Comment by kmiya-culti** [comment]
ベルコード(07)によって警告音を出した場合の動作ですね。

RLoginの設定では・・・
http://nanno.bf1.jp/softlib/man/rlogin/#SCREENOPT
オプション・スクリーン・ベルコード(07)による動作を選択
で動作をSound/None/Both/Visualから洗濯で変更できますがSoundの場合Windowsの警告音を鳴らします

Windows11/10の場合
設定・アクセシビリティ（簡単操作設定）・オーディオ・オーディオ通知中に画面を点滅させる
で画面を反転表示するようなので今回の場合の表示では（ウィンドウ全体が反転表示）なので
こちらのWindowsの設定が問題のようですね

**Comment by cidrugHug8** [comment]
ありがとうございました。解決しました。
