### ISSUE TITLE
現在のタブ表示を分かりやすくして頂けないでしょうか？

### ISSUE THREAD

**Issue by kinchan** [kmiya-culti/RLogin#112]
初めまして、竹内と申します。
まず、RLogin という素晴らしいターミナルソフトを無償で公開して頂いていることに感謝を申し上げます。
本当にありがとうございます。

さて、RLogin を毎日使用させて頂いており、特にタブは重宝しています。
ただ私事ですが老眼のせいもあって、現在表示中のタブがどれかの視認性に少々不便を感じています。
勝手なお願いとは存じますが、現在のタブに任意の色をつけるなど視認性を高める機能を付けて頂けないでしょうか？
色でなくても現在のタブを白抜き（あるいは反転）するとか、視認性を高めるなら何でも構いません。

以上、ご検討頂けると幸いです。
どうぞ今後もよろしくお願い致します。
失礼します。

**Comment by kmiya-culti** [comment]
次期試作版にタブバーの色設定を追加してみました

http://nanno.bf1.jp/softlib/rlogin/2.28.5/

オプションの拡張機能に設定を入れてみました

http://nanno.bf1.jp/softlib/man/rlogin/#EXTOPT

お試しいただければ幸いです。

**Comment by kinchan** [comment]
作者様

私の要望にお答えくださりありがとうございました。
早速試用したのですが、私の希望が完全に叶えられました。
接続ごとに色を分けることも出来るので重宝しそうです。
重ねて御礼申し上げます。
どうぞ、今後もよろしくお願い致します。
失礼します。
