### ISSUE TITLE
2.28.3以降でSSHの多段接続ができなくなりました

### ISSUE THREAD

**Issue by Harbie34** [kmiya-culti/RLogin#113]
これまで2.28.2を使っていて、ホームページの「5.16 SSHによる多段接続」のような方法で接続していたホストがあるのですが、2.28.5にバージョンアップしたところ、つながらなくなりました。順次ダウングレードしてみたら2.28.3からつながらなくなっているようです。エントリー構成(デフォルトから変更した設定)は以下のようになっています。

- エントリーA(踏み台)
  - 「ホスト名」に外部から接続可能なホスト名を設定
  - 「ログインユーザー名」、「パスワード」を設定(パスワード認証を使用)
  - 「シェル起動なしでPFログを表示」をON
  - ポートフォワード設定で「Local Proxy Server」を選択、「Host Name」にlocalhost、「Port」に1080を設定
- エントリーB(外部から隔離された環境)
  - 「ホスト名」にプライベートIPアドレスを設定
  - 「前接続先」にエントリーAを設定
  - 「ログインユーザー名」のみ設定(Pageantによる認証)
  - プロキシ設定で「SOCKS5」を選択、「Proxy Server Address」にlocalhost、「Socket Port」にsocksを設定

再現手順は以下のような感じです。

1. 検証用として空のフォルダに2.28.2を配置、空のRLogin.iniを作成してから起動
2. 「プライベートプロファイルの圧縮を有効にして～」が表示されるので「はい」
3. 上記エントリーの設定をしてエントリーBに接続
4. 「このエントリーで最初のPageantの起動を確認しました～」が表示されるので「はい」を選択、認証キー情報は特に編集せずそのまま「OK」
5. 「公開鍵の確認」が表示されるのでそのまま「接続する」
6. エントリーBに対して再度4と5の操作
7. 「信頼するホスト鍵のリストを更新しますか？～」が表示されるのでそのまま「はい」

これでいったんエントリーBに接続できることを確認後、2.28.3に差し替えて接続しようとしてもつながらない状態です。エントリーBのプロキシ設定で「socks」を「1080」にしてみてもダメでした。また、2.28.2で接続したとき、エントリーAの画面には↓が表示されていましたが、
```
9 13 22:00:00 mypc : Local Socks localhost:1080
9 13 22:00:00 mypc : Connect #3 エントリーBのIP:22 -> ::1:64562
```
2.28.3だと↓しか表示されていませんでした。
```
9 13 22:00:00 mypc : Local Socks localhost:1080
```

Releasesページに「オプション設定のsshポートフォワードの更新を行うように変更」との記載があったので、その辺の影響とかでしょうか…？他に必要な情報があればできる限りご提供したいと思いますのでご確認よろしくお願いいたします。

**Comment by kmiya-culti** [comment]
「シェル起動なしでPFログを表示」を使用するとCONNECT処理されず
前接続先の設定で処理が継続されないバグがありました。

ご報告有り難うございます。次期バージョンで修正したいと思います
http://nanno.bf1.jp/softlib/rlogin/2.28.6/

**Comment by Harbie34** [comment]
早速ご対応いただきありがとうございました。
2.28.6で問題なく接続できることを確認しました。
