### ISSUE TITLE
ssh2 etm mac miss match errorについて

### ISSUE THREAD

**Issue by accept** [kmiya-culti/RLogin#114]
お世話になっております。
SSHにてシェルにアクセスし、そこからDockerコンテナ内のシェルにアクセスして不定期に流れるログを見る用途で使用させていただいているのですが、最近下記画像のようなエラーが発生し、接続が切られてしまう問題が発生しています。

<img width="259" alt="2023-10-20" src="https://github.com/kmiya-culti/RLogin/assets/421679/703d797b-338a-41fd-b8bf-38630fde666a">

<img width="261" alt="2023-10-20 (1)" src="https://github.com/kmiya-culti/RLogin/assets/421679/bfa062a3-4c26-41db-8b09-f0040d013efb">

<img width="263" alt="2023-10-20 (2)" src="https://github.com/kmiya-culti/RLogin/assets/421679/67c82b4d-6130-47d0-8000-dcef50785c9b">

複数台のマシンで同じようにログを出していますが、この問題が発生しているのは1台だけで少なくとも2台はこのエラーが発生していません。
調べても原因が分からず、こちらに投稿させていただきました。
こちらはどのような原因が考えられるでしょうか。
こちらで何か対策や調査をすることは可能でしょうか。
お力添えいただけましたら幸いです。

**Comment by kmiya-culti** [comment]
気になる現象ですね・・・
etm@openssh.comでの処理のバグなら直せる可能性があるのですが・・・

試していただきたいのは・・・
https://kmiya-culti.github.io/RLogin/#SSHPROTOCOL

暗号方式などの設定でSSH2の検証を・・・
hmac-sha2-256-etm@openssh.comなどからhmac-sha2-256などのetm@openssh.comでないものに
入力・出力とも変更してみて挙動が変わるかどうかです。

さらにSSH2の暗号を・・・
aes256-ctrなどからchacha20-poly1305@openssh.comに
入力・出力ともに変更してみてるもの良いかもしれません。

これでも挙動が変わらないならパケットが改変されていることになるので
クライアントとサーバーの両方で動作を検証する必要があることになりますね

**Comment by accept** [comment]
@kmiya-culti 
お忙しい中、こんなにも早くご返信いただきありがとうございます。
なるほど、ありがとうございます。
仕事の関係で少し時間が掛かるかもしれませんが、ご指摘いただいた点を検証してみます。

パケット改変、なるほど…
そちらも念頭に置いて検証してみます。

**Comment by accept** [comment]
@kmiya-culti 
お世話になっております。検証に時間が掛かりましたが問題が解決しました。
原因は使用しているPCにインストールされていたASUS社製のユーティリティソフト、ROG GameFirst VIでした。
使用しているソフトウェアではなかったのでアンインストールしたところ、無事にエラーが解消されました。

マザーボードのドライバを入れる際に一緒に入ったものと思うのですが、このソフトウェアはQoSのような通信の制御をするようで
特に設定をしていなくても入れているだけでゲームなど特定のソフトウェアの通信を優先し、その他を遅くしているようです。
これにより通信が阻害されデータ到達の時間が変動し、暗号の検証に影響が出ていたのではないか、と予想しましたが詳しいところは不明です。

私の環境の問題によりお騒がせしてしまい申し訳ありませんでした。
今後とも末永く、よろしくお願いいたします。
