### ISSUE TITLE
Server Edit Entry - キーボード での削除時の動作

### ISSUE THREAD

**Issue by hhase1973** [kmiya-culti/RLogin#115]
Server Edit Entryのキーボード で一覧からの削除時の動作
削除を行うとカーソールが先頭行に戻ってしまう。
削除した上の行 or 下の行に留まるようにしてほしい。

**Comment by kmiya-culti** [comment]
たしかに酷い仕様ですね・・・
ご報告有り難うございました。

次期バージョンで修正してみました
お試しいただければ幸いです。
http://nanno.bf1.jp/softlib/rlogin/2.29.0/
