### ISSUE TITLE
ダークモードを OFF にできますか？

### ISSUE THREAD

**Issue by aviscaerulea** [kmiya-culti/RLogin#118]
いつも大変便利に使わせていただいています。

2.29.0 からかダークモードが実装されたと思います。
RLogin はライトモードで使いたいと思っているのですが、設定のどこで切替えられるのか教えていただけますかか？

**Comment by kmiya-culti** [comment]
次期バージョンでダークモードの有効を設定できるようにしようと思います

http://nanno.bf1.jp/softlib/rlogin/2.29.1/
http://nanno.bf1.jp/softlib/man/rlogin/#COLOPT
http://nanno.bf1.jp/softlib/man/rlogin/faq.html#WINCOL
