### ISSUE TITLE
IPアドレス手動入力ウィンドウなどの拡大率が高く、ボタンが見切れている (ver 2.29.1)

### ISSUE THREAD

**Issue by yuru7** [kmiya-culti/RLogin#120]
素晴らしいソフトのメンテナンス、いつもありがとうございます。以下、バグ報告です。

- RLogin ver 2.29.1
- Windows設定で画面拡大率は 125% で利用

IPアドレス手動入力ウィンドウやフィンガープリント確認ウィンドウにおいて、下図のように拡大率が高くなりすぎてボタンが見切れてしまいます。
なお各ウィンドウサイズを右下ドラッグで調整してもボタンの見切れは解消できませんでした。

![Untitled](https://github.com/kmiya-culti/RLogin/assets/13458509/75c55467-79af-4353-acf9-ca5a297350b4)

**Comment by kmiya-culti** [comment]
ご報告有り難うございます。
挙動を変更してみました。お試しいただければ幸いです。

http://nanno.bf1.jp/softlib/rlogin/2.29.2/

**Comment by yuru7** [comment]
ボタンが見切れることなく使えるようになったことを確認しました。ありがとうございます！
