### ISSUE TITLE
クライアント側でネットワークの切断が起るとRLoginがフリーズする(v2.29.1)

### ISSUE THREAD

**Issue by ohtanzcom** [kmiya-culti/RLogin#121]
RLoginバージョン：2.29.1
OS：Windows10(64bit) Pro

プロバイダを切り替える必要があり、デフォルトゲートウェイの切り替えを行うことがあるのですが、
切り替えのタイミングでネットワークの切断が発生した際に、RLoginがフリーズします。
この状態になると右上Xボタン等がすべてがクリックできなくなり、タスクから強制終了するしかなくなります。

![image](https://github.com/kmiya-culti/RLogin/assets/69287535/60bd549a-d5f0-4674-b41e-aeb106712e2e)

**Comment by kmiya-culti** [comment]
当方でその症状を確認出来ませんでした。

何か条件があるような感じですが、関係がありそうなブロックしているスレッドを
特定できるようにしたバージョンを作ってみました。
終了処理を行って約５秒間、応答が無いとメッセージを表示します。
そのメッセージ内容をご連絡いただければ幸いです。

メッセージを表示しない場合は、別の部分での不都合なので特定が難しいです。
その場合は、その症状がでる条件を見つける作業が必要となります。

気になる部分として投稿されたスクリーンショットでタイトルのIPアドレスですが
プライベートのようなのでプロキシを使用されているのでしょうか？

http://nanno.bf1.jp/softlib/rlogin/2.29.2/

**Comment by ohtanzcom** [comment]
ありがとうございます。

上記URLのバージョンで試してみたところ、5秒経過してもメッセージは表示されませんでした。

>気になる部分として投稿されたスクリーンショットでタイトルのIPアドレスですが
>プライベートのようなのでプロキシを使用されているのでしょうか？

プロキシは使用しておりません。
上記スクショはプライベートネットワーク内にあるサーバーにアクセスしているものとなります。

今試していて分かったのですが、下記手順を行うと再現します。
1.SSHでサーバーに接続
2.RLoginを最小化する
3.ネットワークを切り替える(回線切断が発生)
4.最小化したRLoginを開く(ここでフリーズ)

※2をせずに3を行うと、フリーズせずに再接続のポップアップが表示されます。


よろしくお願いいたします。

**Comment by kmiya-culti** [comment]
確認出来ました。おもしろい症状でした・・・
本体は、フリーズしていません。メッセージボックスの
ダイアログが表示されない状態になりました。

メッセージボックスの入力待ち状態なのに表示されていないので
フリーズしたように見えますがエンターキーなどのキー入力や
マウス操作も見えないダイアログが保持しています

メッセージボックスの表示時にアイコン状態なら復帰するように変更しました
ご報告有り難うございました。

**Comment by ohtanzcom** [comment]
>マウス操作も見えないダイアログが保持しています

なるほど、すごく腑に落ちました。

修正いただきありがとうございます。
