### ISSUE TITLE
2.29.2でメニューの挙動が変わった

### ISSUE THREAD

**Issue by Cudo29** [kmiya-culti/RLogin#122]
2.29.2に更新してから以下の現象が発生しています。

- いずれかの接続を行っているとメニューバー自体が表示されなくなり、メニュー操作もできません（例えば、Alt+E、V で貼り付けができていましたができなくなりました）
- メニュー項目から「編集（E）」がなくなっています。
- 非接続時、「編集（E）」以外の項目（ファイル（F）、表示（V）、ウインドウ（W）、ヘルプ（H））は表示されていますが、このうち表示とウインドウは　Alt＋キー　を入力してもサブメニューが開きません。

アプリケーション側の問題なのか、当方の環境に依存する問題なのか、あるいはその両方なのかはまだ分かりませんが、
2.29.1 以前の挙動に戻していただけたら、あるいは戻す方法が分かればご教示いただけたらありがたいです。
以上、お手数おかけしますが修正の程ご検討お願いいたします。

なお現象を確認した環境は Windows11 Home 23H2（OSビルド 22631.3296）です。

**Comment by kmiya-culti** [comment]
単純にメニューバーが非表示のような感じですが・・・

非接続時には、メニューバーが非表示でも表示するようにしていますので
表示メニューのメニューバーにチェックがあるか確認できます。

タイトルバーのアイコンをクリックしてシステムメニューからも
メニューバーの表示・非表示が出来るようにしています

https://kmiya-culti.github.io/RLogin/faq.html#WINVIEW

**Comment by Cudo29** [comment]
ご指摘の通り、メニューバーが非表示になっていることが原因でした。
お騒がせし失礼しました。
