### ISSUE TITLE
Can I change the SFTP transfer window color?

### ISSUE THREAD

**Issue by superuser7777** [kmiya-culti/RLogin#123]
Thank you for the great software!

I use dark mode every day.
Is there an option to dark mode the SFTP window as well?

**Comment by kmiya-culti** [comment]
SFTPのダークモード対応との事ですがタイトルバーやツールバーは、
対応していますが、リストボックスやコンボボックスは、適応していません

これらは、Win32アプリケーションのダークモード対応をOSに依存している部分で
現状で得られる情報では、好ましい対応が行われていないので適応しませんでした
将来的に新しい情報や変化があれば対応したいと考えています

-- automatic translation --
SFTP is compatible with dark mode, but the title bar and toolbar are
It is supported, but list boxes and combo boxes are not.

These are the parts that depend on the OS to support dark mode in Win32 applications.
The information currently available does not indicate a desirable response, so we did not apply it.
We would like to respond to any new information or changes in the future.

**Comment by kmiya-culti** [comment]
2.29.3から各種コントロールもダークモードに対抗しました
まだ、気になる部分もありますが、それなりにダークモードに見えます

-- automatic translation --
From 2.29.3, various controls have also been made compatible with dark mode.
There are still some areas of concern, but it looks like dark mode.

**Comment by superuser7777** [comment]
Perfect job!
