### ISSUE TITLE
Can I launch RLogin through command line?

### ISSUE THREAD

**Issue by byeonlab** [kmiya-culti/RLogin#124]
Can I launch RLogin through command line?

For example, I can use "putty.exe [-ssh | -telnet | -rlogin | -raw] [user@]host" in windows cmd.
Does RLogin support this feature?

**Comment by kmiya-culti** [comment]
日本語でのマニュアルしかありませんが記載があります

-- automatic translation --
There is only a manual in Japanese, but there is a description

https://kmiya-culti.github.io/RLogin/#CMDLINE

**Comment by byeonlab** [comment]
ありがとうございます

**Comment by byeonlab** [comment]
ありがとうございます
