### ISSUE TITLE
Bash で Ctrl+R によるコマンド履歴呼び出し時の挙動がおかしい

### ISSUE THREAD

**Issue by aviscaerulea** [kmiya-culti/RLogin#125]
使用しているのは RLogin 2.29.2 です。

SSH 接続している Linux リモートのターミナルで、Ctrl+R によるコマンド履歴を呼び出して、左右のカーソルを押下したときに履歴コマンドが反映されることを期待しているのですが、プロンプトが表示されてしまいます。

![20240408_142401](https://github.com/kmiya-culti/RLogin/assets/1040522/53a39b9e-eeea-4435-a8c9-0b1ccad56daf)

以下のような具合です。
"(reverse-i-search)" の表示位置もおかしい？

```
[root@host]$    (※ Ctrl+R 入力)
[root@host]$ (reverse-i-search)`ls': ls /home   （※ここで右カーソルを入力）
[root@host]$ (reverse-i-search)`ls': [root@host ]$         | ← カーソル位置
```

ただ、表示されている内容と異なり、履歴で選択したコマンド自体は反映されているようなので上記の状態からエンターすると選択した履歴のコマンドが実行されます。
接続設定を「プログラムの初期値まで戻す」でリセットしたもので行っても変わりませんでした。

試しに切り分けのため同ホストに TeraTerm 5.0 で行うと、こちらは期待通りの挙動でした。
![20240408_142634](https://github.com/kmiya-culti/RLogin/assets/1040522/44234170-44d7-4687-a136-a45bed146775)

これは何処かの設定で調整できたりしますか？

**Comment by aviscaerulea** [comment]
加えて Ctrl+R ではなく、プロンプトで上下カーソルキーで履歴を辿ろうとすると、プロンプトと履歴のコマンドが行末に追記されていってしまうような動きもあります。

本題の現象も含めてパッと見で CR が抜けてしまっているような挙動をしています。（あくまでイメージとして）

**Comment by kmiya-culti** [comment]
よくある問題としてTERM環境変数の設定があります。
ご確認ください

https://kmiya-culti.github.io/RLogin/faq.html#TERM

**Comment by aviscaerulea** [comment]
ありがとうございます。
TERM 環境変数は vt100, vt220, xterm, xterm-256color のいずれを設定しても動作は変わりませんでした。
環境としては、RLogin のバージョンを都度上げていった以外に接続先ホストの環境は何も変わっていないのですが、そのような場合でも TERM 環境変数の調整が必要になったりするものだったりしますか？

**Comment by aviscaerulea** [comment]
別環境として Windows サンドボックス上で試したところ、同ホストに対して RLogin 2.29.2 で期待通りの動作をしました。

接続設定を「プログラムの初期値まで戻す」で初期化したつもりだったのですが、それでも TERM 環境変数周りは初期化されないものがあるのでしょうか？

また、この場合に問題が生じている Windows ホスト上で接続先情報（できればパスワードも）を保持した上で、TERM 環境変数周りなど問題を起こしている設定などをクリーンにする方法はありますか…？

**Comment by kmiya-culti** [comment]
ひょっとして受信した改行コードの設定でしょうか・・・

http://nanno.bf1.jp/softlib/man/rlogin/#TERMOPT

**Comment by aviscaerulea** [comment]
おお…、それでした！
いくつかの環境で確認して、この件が期待通りの動きになりました。
自分の環境では `LF` になっていたので、`CR+LF` にしました。

この項目は設定初期化の影響を受けないものになっているんですね。
安直にリセットすればいいだろうと思って、改行コードの設定は気にしていませんでした…。

ありがとうございました。

**Comment by aviscaerulea** [comment]
close
