### ISSUE TITLE
rlogin_x64-2.29.3で「ヘルプ」→「rloginのバージョン情報」を開くとハングアップする

### ISSUE THREAD

**Issue by himazin-blm** [kmiya-culti/RLogin#126]
rlogin_x64-2.29.3で「ヘルプ」→「rloginのバージョン情報」を開くとハングアップする。
タスクマネージャーで電力消費：非常に高い、電源の使用率：低な状態のまま何も操作できなくなる。
rlogin_x64-2.29.2では問題なし。
OS：Windows 10 Pro 64bit（22H2）・ローカルアカウント
　OS ビルド：19045.4291
　エクスペリエンス：Windows Feature Experience Pack 1000.19056.1000.0
プロセッサ：Intel(R) Core(TM) i3-10105 CPU @ 3.70GHz   3.70 GHz
RAM：16.0 GB (15.8 GB 使用可能)

追記：下記環境では正常に動作した。
OS：Windows 11 Pro (23H2)・Microsoft アカウント
　OSビルド：22631.3447
　エクスペリエンス：Windows Feature Experience Pack 1000.22688.1000.0
プロセッサ：12th Gen Intel(R) Core(TM) i9-12900H   2.50 GHz
RAM：16.0 GB (15.7 GB 使用可能)

**Comment by kmiya-culti** [comment]
#128 と同じ原因のようです
以降 #128 で対応したいと思います。
