### ISSUE TITLE
ダークモードの時に接続先の選択画面でどのエントリが選択状態になっているのかがわかりにくい

### ISSUE THREAD

**Issue by yasuhirokimura** [kmiya-culti/RLogin#127]
Windows 11 23H2でRlogin 2.29.3を使用しています。

OSの設定がダークモードになっている状態で「ファイル」→「サーバに接続」を実行して接続先を選択するダイアログが表示された場合、背景色が濃い灰色(?)で文字の色が白となりますが、この時選択状態になっているエントリの行の背景色が(推測ですが)ライトモードの時と同じ色が使われているため、どのエントリが選択状態になっているのかがわかりにくいです。

ダークモードで選択状態になっているエントリの行の背景色をわかりやすい色に変更していただけないでしょうか。

よろしくお願いします。

**Comment by kmiya-culti** [comment]
#123 で書きましたが気になる部分の１つです。
リストやツリーの選択時の色やディセーブル時の重ね文字表示など
OS側で処理される為にアプリでは、簡単に変更できません
タブコントールでは、すべてアプリで作り直しましたが、大変でした・・・

**Comment by yasuhirokimura** [comment]
なるほど。アプリ側からは簡単に変更出来ないのですね。ご説明ありがとうございました。
