### ISSUE TITLE
ウィンドウが存在しない状態でアプリのCPU使用率が上がる

### ISSUE THREAD

**Issue by yasuhirokimura** [kmiya-culti/RLogin#128]
OS: Windows 11 23H2
RLogin: 2.29.3

RLoginを起動すると接続先を選択するダイアログが表示されますが、ここで「キャンセル」ボタンを押してダイアログを消すとプロセスのCPU使用率が上昇します。
「ファイル」→「サーバに接続」を選択して接続先選択ダイアログを表示するとCPU使用率が下がります。

**Comment by yasuhirokimura** [comment]
これと関係があるのかわかりませんが、ウィンドウが存在しない状態で「ヘルプ」の

* RLoginのバージョン情報
* セキュリティポリシーの設定
* 各種ウィンドウの色設定
* ダイアログフォントの設定
* ツールバーのカスタマイズ

を選択するとマウスによる操作を受け付けなくなります。これらに付いてはエスケープキーを叩くと正常に戻るようですが、

* プライベートプロファイル作成
* レジストリをファイルに保存

を選択した場合にはプロセスが応答なしの状態に陥って強制終了するしかなくってしまいます。

**Comment by kmiya-culti** [comment]
#126 も同じ内容のようですね・・・
当方で色々と条件を変えてテストしていますが再現できていません

原因の特定が出来ないので申し訳ごさいませんがテストをお願いできないでしょうか
http://nanno.bf1.jp/softlib/rlogin/2.29.4/

2.29.3で追加したコントロールのダークモード対応を元に戻してみました
これで同じ症状の場合は、openssl-3.3.0に変更したのが原因かもしれません
よろしくお願いいたします。

**Comment by bsdmad** [comment]
いつも便利に使わせていただいています。

> 原因の特定が出来ないので申し訳ごさいませんがテストをお願いできないでしょうか http://nanno.bf1.jp/softlib/rlogin/2.29.4/
します。

2.29.3 で #126 と同様の症状になったのですが、2.29.4 では症状が改善されませんでした。
（Windows11 23H2、OSビルド 22631.3447 です）

**Comment by yasuhirokimura** [comment]
> 原因の特定が出来ないので申し訳ごさいませんがテストをお願いできないでしょうか http://nanno.bf1.jp/softlib/rlogin/2.29.4/

この下にあるrlogin_x64.zipをダウンロードして試してみましたが、最初に報告した症状・追加で報告した症状のいずれについても改善されませんでした。

**Comment by yasuhirokimura** [comment]
RLoginを2.29.2に戻してみたところいずれの症状も発生しなくなりました。

**Comment by kmiya-culti** [comment]
ご協力有り難うございます。
openssl-3.3.0をopenssl-3.2.1に戻した物を作成してみました。
これで症状が改善するなら原因を少し絞ることができます
http://nanno.bf1.jp/softlib/rlogin/2.29.4/

何が原因でその症状が出るのか特定したいのですが、
当方で再現できないので難しいです・・・

**Comment by himazin-blm** [comment]
当方でも上記の2.29.4（5/1 8:27）を試してみましたが、状況は変わりませんでした。
上記例と同様に2.29.2に戻せば問題はありません。

**Comment by yasuhirokimura** [comment]
私も更新された2.29.4の64bitバイナリを試してみましたが症状に変化はありませんでした。

**Comment by kmiya-culti** [comment]
タブバーを常時表示にしているとそのような症状になることを確認しました。
メニュー・表示・タブバーのチェックを解除して改善できないでしょうか？

**Comment by yasuhirokimura** [comment]
@kmiya-culti 確かに「表示」→「タブバー」にチェックが入っていました。
2.29.3でチェックを外したところいずれの症状も発生しなくなりました。

**Comment by himazin-blm** [comment]
こちらでもタブバーのチェックを外すことで回復しました。
正常動作していた方の環境ではタブバーのチェックが入っていない状態だったことも確認できました。

**Comment by kmiya-culti** [comment]
色々とデバッグに付き合ってもらいご協力ありがとうございました。
無事に原因が特定できて助かりました。次回バージョンで修正します
