### ISSUE TITLE
登録されたホスト鍵の一覧でホスト鍵が正常に表示されない

### ISSUE THREAD

**Issue by yasuhirokimura** [kmiya-culti/RLogin#129]
OS: Windows 11 23H2
RLogin: 2.29.3

1. 「ヘルプ」→「登録されたホスト鍵の削除」で表示される全てのホスト鍵を削除
2. *eastasia*と*rolling-vm-freebsd2*というホスト名のホストにそれぞれ接続
3. 「ヘルプ」→「登録されたホスト鍵の削除」でホスト鍵の一覧を表示

とすると以下のようになります。

<img width="948" alt="RLogin HostKeyList" src="https://github.com/kmiya-culti/RLogin/assets/5249848/9a63caf0-07f1-4726-8758-ec1be58f2cbc">

この2つのホストはアーキテクチャ・OSの種類及びバージョンが同じで、動作している`sshd`のバージョンも同じなのですが、*eastasia*については三種類のホスト鍵が表示されているのに対して、*rolling-vm-freebsd2*については、ホスト名から *'-freebsd2'* が省かれており、またホスト鍵が*eastasia*と同様に三種類登録されているはずですが、それらが表示されません。

この後色々な名前のホストに接続してみたのですが、*abcdefg-hi-stuvwxyz*のようなホスト名だと二番目のハイフン以降が省かれる＆ホスト鍵が表示されないという症状が発生するようです。

**Comment by kmiya-culti** [comment]
ご報告有り難うございます。確認できました。
バージョン2.28.2で「非対応の鍵でもagentでは、利用するように変更」で
鍵の判定を変更した時の影響で古い形式のエントリーと誤判定していました。

次回バージョンで修正したいと思います。
http://nanno.bf1.jp/softlib/rlogin/2.29.4/
