### ISSUE TITLE
パスワードロック使用時の複数PCでの利用について

### ISSUE THREAD

**Issue by mizuki-m0** [kmiya-culti/RLogin#13]
大変使いやすくいつも利用させてもらっています。

私は複数PCで利用できるように(同時ではありません)、NAS上にプログラムを設置して使っています。
パスワードロックをONにしておくと別PCからの起動時に、パスワードを入力しても解除ができない現象が起きております。(解除に各PC固有の値を使っているのでしょうか？)
セキュリティを高めるための仕様と言われてしまうとあれなのですが、可能であればPC間を移動してもパスワードのみで解除できるようにしていただけると幸いです。

利用環境は
設置場所：ネットワークドライブ(SAMBAでアクセス)
PC：Windows10 x64 1709 (Home,Proどちらでも発生)

よろしくお願いします。

**Comment by kmiya-culti** [comment]
すべてのパスワードは、実行したパソコンの固有名と一緒に符号化してチェックしています。これは、単純ながら安易なコピーで使用できなくするための処置です。たしかにパスワードロックでは、必要ないかもしれませんが、セキュリティー的には、外したくありませんね。

これが問題になると言うことは、プライベートプロファイルで使用されていると思うのですが、同時起動などを考えるとあまりにも簡単にプライベートプロファイルが破損すると思います。

**Comment by mizuki-m0** [comment]
返信ありがとうございます。
上にも書きましたが同時起動はしませんので破損に関しては問題ないかと思います。
WinSCPと合わせて使うことが多いので同じ仕様だったらと思った次第です。

もしよろしければオプション等で指定などできると嬉しいです。これからも使わせていただきます。
