### ISSUE TITLE
Alt + -キー入力でWindowsのキー入力がおかしくなる

### ISSUE THREAD

**Issue by x03n046** [kmiya-culti/RLogin#130]
OS: Windows10 22H2
RLogin: 2.29.3

"alt" + "-"キーが入力されるとWindowsのキー入力やマウスクリックが一部受け付けなくなりました。
他の環境でも試しましたが、この事象は再現します。

お手数ですがこの事象について御確認下さい。

**Comment by kmiya-culti** [comment]
確認できました。次回バージョンで修正したいと思います
ご報告有難うございました。

http://nanno.bf1.jp/softlib/rlogin/2.29.4/

**Comment by x03n046** [comment]
御確認頂きましてありがとうございます。

リンク先のバージョン2.29.4では、
この事象が改善されていることを確認しました。
