### ISSUE TITLE
2.29.3以降で、複数行貼付時の確認ウィンドウでの表示不具合

### ISSUE THREAD

**Issue by sato-fu** [kmiya-culti/RLogin#131]
version 2.29.3以降、ターミナルに複数行を貼り付けた際の確認ウィンドウにおいて、文字列を編集すると、文字が重なって表示されたり、削除した文字が表示上消えないという現象が見られます。
version 2.29.2以前のバージョンでは問題は発生しません。
![2 29 4](https://github.com/kmiya-culti/RLogin/assets/20219637/9a063030-317a-40f2-8522-fb4784a9e314)

**Comment by kmiya-culti** [comment]
確認できました。次回バージョンで修正したいと思います。
ご報告有り難うございました。

http://nanno.bf1.jp/softlib/rlogin/2.29.5/
