### ISSUE TITLE
2.29.5 ssh2ポートフォワード付きサーバ複数タブ 2番目タブはInvalid open failure channel id エラーが発生。

### ISSUE THREAD

**Issue by clfsoft** [kmiya-culti/RLogin#132]
ver: 2.29.5
os:windows 10

ssh2ポートフォワード付きサーバ複数タブ接続したい、
2番目タブはInvalid open failure channel id エラーが発生。
2番目タブが接続できない

同じ設定ファイルで、v2.27.7.0実行ファイルの場合、問題がないです。

エラー内容：
![image](https://github.com/kmiya-culti/RLogin/assets/1608414/06ab6fdf-f7b0-4254-9574-39f33b04124e)

設定内容：
![image](https://github.com/kmiya-culti/RLogin/assets/1608414/ab85c28c-9457-430f-ae83-32aec906e067)

**Comment by kmiya-culti** [comment]
確認できました。次回バージョンで修正したいと思います。
ご報告有り難うございました。

http://nanno.bf1.jp/softlib/rlogin/2.29.5/

**Comment by clfsoft** [comment]
> 確認できました。次回バージョンで修正したいと思います。 ご報告有り難うございました。
> 
> http://nanno.bf1.jp/softlib/rlogin/2.29.5/

上記のバージョン問題なく、接続できました。ありがとうございました。
