### ISSUE TITLE
余計なメッセージ「別のチャンネルが開いています。閉じますか？」またはメッセージの2重表示

### ISSUE THREAD

**Issue by clfsoft** [kmiya-culti/RLogin#133]
ver: 2.29.5(2024/06/21)
os: win10 22h2

問題１：
余計な「別のチャンネルが開いています。閉じますか？」の表示
１．サーバ設定に`ポートフォワード`の設定があります
![image](https://github.com/kmiya-culti/RLogin/assets/1608414/99b3a8eb-1dea-4c58-9551-5e9d10284d9d)

２．サーバ接続を閉じると「現在、接続中です。接続を閉じますか？」の表示→はい選択
３．「別のチャンネルが開いています。閉じますか？」が表示されますが。　　
どちら選択しても結果が同じ。「２．」で既にポートなどが閉じた。
![image](https://github.com/kmiya-culti/RLogin/assets/1608414/fbea4e35-54ba-458f-8e0c-ee89f7a9dbd9)

期待する振舞は
「３．」のメッセージ表示なしで、そのまま接続閉じること
  
---
  
問題２：（おそらく問題１とかかわりがある。`ポートフォワード`がない場合問題がない）
「現在、接続中です。接続を閉じますか？」のメッセージが２重表示
１．サーバ設定に`ポートフォワード`の設定があります
２．サーバ設定に`接続が切れると自動でプログラムを終了する`はＯＮ
３．サーバ接続を閉じると「現在、接続中です。接続を閉じますか？」の表示→はい選択
４．「現在、接続中です。接続を閉じますか？」と「別のチャンネルが開いています。閉じますか？」が重ねて表示された。
（画像は一つメッセージウィンドウ移動したもの）
![image](https://github.com/kmiya-culti/RLogin/assets/1608414/cabf5717-556d-4660-8e79-4461b452b43e)

**Comment by kmiya-culti** [comment]
確認できました。次回バージョンで修正したいと思います
ご報告有り難うございました。

http://nanno.bf1.jp/softlib/rlogin/2.29.6/

**Comment by clfsoft** [comment]
早速の対応ありがとうございます。
下記のバージョンで問題が解消しました。

> 確認できました。次回バージョンで修正したいと思います ご報告有り難うございました。
> 
> http://nanno.bf1.jp/softlib/rlogin/2.29.6/
