### ISSUE TITLE
ターミナル画面上のハイパーリンク

### ISSUE THREAD

**Issue by btbf** [kmiya-culti/RLogin#135]
他のターミナルでは画面上に表示されるhttps~ URLに対して自動的にハイパーリンクがかかるものもありますが、r-loginでは実装検討可能でしょうか？もしくは既に設定画面でオン/オフ可能でしょうか？

**Comment by kmiya-culti** [comment]
多少面倒ですが・・・

クリップボードのオプション設定に
”http:で始まる文字列をコピーすると自動でブラウザを起動します”
のチェックがあります。

この機能を実装する時にURL文字列の切り出しが難しいのでユーザー任せにした記憶があります
URLの開始文字列の特定は、簡単なんですが、終了文字列が確定出来なかったはずです

https://kmiya-culti.github.io/RLogin/#CLIPOPT

**Comment by btbf** [comment]
ご回答ありがとうございます！
既に便利な機能が実装されていたんですね。
こちらを使用させていただきます。
