### ISSUE TITLE
サーバ接続直後にドラッグアンドドロップでファイル転送を行うと、プログラムが終了する

### ISSUE THREAD

**Issue by mee1080** [kmiya-culti/RLogin#136]
サーバに接続した直後に、ドラッグアンドドロップでファイル転送を行うと、時々プログラムが終了します。

* 接続後に5秒程度待てば、問題なく転送できます。
* 意図的に操作すれば、体感として8割ぐらいの確率で発生します。
* Server Selectのダイアログで、ダブルクリックでサーバを開くと、OKボタンやキーボード操作で開いた場合より、発生率が高いです。
* サイズ8KBのファイルで発生しました。

バージョン2.29.7で初めて発生し、2.29.8でも発生しました。OSはWindows 11です。

**Comment by kmiya-culti** [comment]
ファイルのドラッグアンドドロップでSCPを選択するとプログレスウィンドウの書き換え前に
ファイル転送が終了すると落ちる現象を確認しました。

次回バージョンで修正したいと思います。ご報告有り難うごさいました。
