### ISSUE TITLE
タブ複数状態で「すべての状態を保存」し、それを再開した時にどのタブにフォーカスをあてるか指定できますか？

### ISSUE THREAD

**Issue by kinchan** [kmiya-culti/RLogin#137]
RLogin には毎日、大変お世話になっております。改めて感謝申し上げます。

さて、タブが複数ある状態を「すべての状態を保存」で保存し、それを再開したときにどのタブにフォーカスが当たるか指定することはできるのでしょうか？
出来るなら「すべての状態を保存」したものを再開する時、指定したタブにフォーカスが当たった状態で再開したいのですがやり方がありましたらご教示下さい。
あるいは、「すべての状態を保存」する時にタブのフォーカス情報も一緒に保存して頂けると個人的には嬉しいです。
細かい点で恐縮ですがご教示、あるいはご検討、お願い申し上げます。
失礼します。

**Comment by kmiya-culti** [comment]
現在は、再開時のフォーカスに意識は、ありませんでした。
保存時の最後のペインにフォーカスで再開していますが、わかりにくいですね・・・

次回バージョンで”「すべての状態を保存」する時ににタブのフォーカス情報も一緒に保存”
に修正したいと思います。ご提案有り難うございます。

http://nanno.bf1.jp/softlib/rlogin/2.29.9/

**Comment by kinchan** [comment]
開発者様

私の要望に迅速なご対応を賜り誠にありがとうございます。
私にとって RLogin は欠かせないアプリとなっています。
この様な素晴らしいアプリを無償公開されていることに重ねて感謝いたします。
失礼します。
