### ISSUE TITLE
RLogin-2.29.9のrlogin_x64.zipでウィルスが検出される

### ISSUE THREAD

**Issue by yasuhirokimura** [kmiya-culti/RLogin#138]
本日公開されたRLogin-2.29.9の`rlogin_x64.zip`をGoogle Chromeでダウンロードしようとすると「ウィルスが検出されました」と言われてダウンロードすることが出来ません。
また別の方法で`rlogin_x64.zip`をダウンロードした上でWindows 11のMicrosoft Defenderでアーカイブをスキャンすると*Trojan:Script/Wacatac.B!ml*というウィルス(?)が検出されます。
恐らく誤検出なのではないかと思いますが、念のためご報告まで。

**Comment by kmiya-culti** [comment]
確認できましたが、保護の更新を行うと大丈夫なようです。
セキュリティインテリジェンスのバージョン: 1.419.697.0
でウィルス検出されないようです

**Comment by yasuhirokimura** [comment]
Windows Updateで定義ファイルを更新したところ、こちらでも正常にダウンロードできるようになりました。
お騒がせして申し訳ありません。
