### ISSUE TITLE
昔なつかしのFDCloneの使用時の事象について

### ISSUE THREAD

**Issue by josys-one** [kmiya-culti/RLogin#139]
RLoginでファイラー「FDClone」を使用した際、FDClone上で何かテキストファイルとかシェルファイルをエンターキーで表示し、qキーでファイル一覧に戻った後、上下左右矢印キーを押下すると、FDを終了しますか？となり、その他のファイル選択が出来ず、FDCloneを終了するしかなくなります。すべて調べたわけではありませんが他のSSHクライアントでは、この現象は発生しません。RLoginでの設定などでこの現象を回避できるのであれば教えていただけないでしょうか。よろしくお願い致します。

**Comment by kmiya-culti** [comment]
確認できました。

原因は、FDが外部プログラム終了後に画面とモードを復帰する時に・・・
DECSET 1
DECPAM
DECSET 1049
としていますが、RLoginでは、DECSET 1049でオプションを復帰しますので
DECSET 1が前の状態に戻ってしまいCKMがセットされないようでした。
CKMは、ステータスバーの”ACVL”の"C"で確認できます。

対応としては、TERM環境変数を確認してtermcap/terminfoの
ti/teで\E[?1049l/hを含まないものにすれば良いと思いますが
次期バージョンのRLoginで?1049オプションの動作を修正したいと思います

ご報告有り難うございました。

**Comment by josys-one** [comment]
お調べ頂きましてありがとうございます。次期バージョンアップをお待ちします。よろしくお願い致します。

**Comment by josys-one** [comment]
RLogin バージョン２．３０．０にて、FDCloneを通常使用できることを確認致しました。これからも愛用させて頂きます。これにて本件、クローズとさせていただきます。迅速なご対応、本当にありがとうございました。
