### ISSUE TITLE
大きなファイルの転送について

### ISSUE THREAD

**Issue by redwish** [kmiya-culti/RLogin#14]
田中ともうします。

rlogin 便利に使わせてもらっています。

ただ、大きなファイルを転送すると途中で止まってしまう現象に見舞われています。
必ずとまるわけではないですが、かなりの確立でとまります。
知人は700MB以上になると止まりやすい、といっています。

環境の問題かもしれませんが、調査方法ないしは回避方法などがありましたらお教え願えますか。
よろしくお願いします。

**Comment by kmiya-culti** [comment]
残念ながら状況を確認できません。
面倒だと思いますが、出来るだけ詳しく環境や操作のご説明をお願いします。

**Comment by redwish** [comment]
環境は以下のとおりです。

rlogin 2.23.0
Windows 10 ver 1709
Memory 16GB

社内で使用しておりルーターはRTX1210ですが途中いくつかHUBが挟まれています。
後は、どのようなことお伝えすればよいでしょうか

**Comment by kmiya-culti** [comment]
これが直接的な原因かどうか判りませんが、2.23.3からTCP/IPの帯域制限を追加してみようと思います。

http://nanno.dip.jp/softlib/man/rlogin/#TRSOPT
http://nanno.dip.jp/softlib/rlogin/2.23.3/

高機能なルーターでは、細かい制限が設定できるようなので通信速度を落とす設定があっても良いかと思いました。実際の動作は、なかなか正確に制御出来ていませんがそれなりに速度を低下されることが出来ます。

**Comment by redwish** [comment]
ご対応ありがとうございます。
ご面倒をおかけしました。
