### ISSUE TITLE
RLogin-2.30.0の64bit版でウイルスが検出されました

### ISSUE THREAD

**Issue by kiiro** [kmiya-culti/RLogin#140]
RLogin-2.30.0
[rlogin_x64.zip](https://github.com/user-attachments/files/17895431/rlogin_x64.zip)

こちらをダウンロードしたところ、Windowsセキュリティにウイルスが検出されたとなり、ダウンロードが出来ません。
何度か試みましたが、結果は同じでした。

検出されたのは
`Trojan:Script/Wacatac.B!ml`
https://www.microsoft.com/en-us/wdsi/threats/malware-encyclopedia-description?name=Trojan%3AScript%2FWacatac.B!ml&threatid=2147735503

となっています。
なお、同バージョンの32bit版や過去のバージョンでは問題有りません。

誤検知かもしれませんが、ご確認をお願いいたします。

**Comment by ntmukai** [comment]
私の環境でも同じでしたが、今改めてダウンロードすると問題ありませんでした。
Windows Defender側の問題だったのかもしれません（当てずっぽうです）。
