### ISSUE TITLE
[BUG]Socket Portにサービス名を指定したサーバーエントリーを再編集した時の挙動

### ISSUE THREAD

**Issue by hogeo** [kmiya-culti/RLogin#15]
Socket Portにサービス名を指定したサーバーエントリーを作成した後再編集するとSocket Portの値がプロトコルのデフォルト値に戻される。
（Socket Portに数値を指定した場合は問題ない）

例
プロトコル: telnet / Socket Port: http でサーバエントリを作成し再編集
プロトコル: telnet / Socket Port: telnet になる

**Comment by kmiya-culti** [comment]
確認出来ました。次期バージョンで修正しようと思います。
ご報告有り難うございました。
