### ISSUE TITLE
RLogin.iniを複数マシンで利用した際の、公開鍵関連の挙動

### ISSUE THREAD

**Issue by Mine02C4** [kmiya-culti/RLogin#16]
とても便利に使わさせていただいております。以下、シンプルにバグらしき挙動を報告します。

# 使用条件

OS: Windows 10 x64 (2018/04/09 時点最新)
RLogin Ver.: 2.23.3 (2018/03/30)

OneDrive上に RLogin.exe を置き、 RLogin.ini を利用している。
2台(デスクトップ,ノートパソコン)で利用しており、出先ではノートパソコン、家ではデスクトップパソコンから利用している。ここではそれぞれ、PC1、PC2とする。

接続先(Server1)へは公開鍵認証を用いて接続している。

# 再現手順

- PC1でServer1へ接続する設定を追加
- サーバー → プロトコルの「認証キー」から当該する鍵セットを追加する。
- 接続を開始すると「SSH鍵ファイルの読み込み」が出て、通常通り公開鍵認証ができる。
- PC1で設定ファイルの同期を確認の後、シャットダウン。
- PC2で設定ファイルの同期を確認して、RLoginを起動。
- 上で追加したエントリからログインを試みる。

すると、本来であれば「SSH鍵ファイルの読み込み」が出てきそうなところですが、パスワード認証用のパスワード入力ダイアログが出てきます。
ここで、パスワードを空にしたままEnterを押すと「SSH鍵ファイルの読み込み」が出てきて、公開鍵認証ができます。

**Comment by kmiya-culti** [comment]
プライベートプロファイルやサーバー情報を保存、レジストリをファイルに保存などは、パスワードを複数のパソコンで共有することは、出来ません（最低限のセキュリティです）

また、「パスワード認証用のパスワード入力ダイアログ」では、ありません。公開鍵認証用のパスフレーズ入力もかねています。以前にも同じような話があったので「password/phase」に修正したのですがタイトルを変更するのを忘れていたようです。

次回バージョンで「パスワード入力」ダイアログの名前を「パスワード/パスフレーズ入力」に修正するようにしようと思います。
