### ISSUE TITLE
「SSH鍵ファイルの読み込み」ダイアログのパスフレーズについて

### ISSUE THREAD

**Issue by odasusu** [kmiya-culti/RLogin#17]
# バージョン
* RLogin 2.23.3 x64
* Win10 Pro 1709
* CentOS 7

# 再現手順
1. 「Server Edit Entry」→「プロトコル」→「認証キー」でキーを設定
1.  認証キーを設定したサーバに接続

# 内容
1. 「SSH鍵ファイルの読み込み」ダイアログのパスフレーズに****が表示される。
2. そのまま、「OK」を押すと「作成時に指定したパスフレーズと一致しません」と表示される。
3. パスフレーズを入力しなおすと正常に接続される。

# その他
RLogin起動時に設定できるパスワードと似たようなダイアログですが
SSH鍵では未入力の段階で****が表示されるので気になりました。仕様でしょうか？

**Comment by kmiya-culti** [comment]
サーバーのオプション設定で設定するpassowrd/phaseは、公開鍵認証の場合は、認証鍵のパスフレーズになります。

http://nanno.dip.jp/softlib/man/rlogin/#SERVEROPT

何度も同じような質問があり、かなり理解しづらい仕様と思います・・・
サーバーオプションダイアログでの表示を全面的に修正したほうがよさそうです。

**Comment by odasusu** [comment]
passowrd/phaseに入力した文字列だったんですね、理解しました。
ユーザ認証→認証鍵と順に設定したので混乱してました。

UI改修、分かりやすくなってるとなってると思います！
あと、こちらのダイアログに```パスフレーズは、"Server Edit Entry->サーバ->ホスト設定"で保存できます。```と表示してはどうでしょうか？
![default](https://user-images.githubusercontent.com/13343833/39046488-56eb1d64-44d1-11e8-9124-e1ffe464903b.PNG)
