### ISSUE TITLE
COM通信にて送信不可？

### ISSUE THREAD

**Issue by akirawk** [kmiya-culti/RLogin#2]
Windows10 64bit 管理者権限で実行してCOMで通信をするも、送信が出来ません。
シリアル通信の設定には問題が無いと思います。
他、設定ミスでしょうか？

**Comment by kmiya-culti** [comment]
状況を判断するだけの情報がなさ過ぎますが・・・

> Windows10 64bit 管理者権限で実行してCOMで通信をするも、送信が出来ません。

この意味としては、「するも、」ですから「管理者権限の実行に関係なく送信が出来ない」でいいでしょうか？管理者権限の実行によって状況が変化するようにも取れますがその場合は、詳しく状況を教えてください。

さらに「送信が出来ません」ですから受信は、正常に行えていると解釈すると「シリアル通信の設定」で送信に関係する部分が問題かもしれません。フロー制御の設定もしくわRS232Cの結線(CD/CTS)でしょうか？

それともTera Termなどの別のアプリでは、正常に送信できると解釈するとCOMデバイスのドライバーとのRLoginとの相性問題になるかもしれません。その場合は、かなり面倒なデバッグ作業となる可能性があります（以前にも同じように問題があってデバッグプログラムを色々と実行してもらって大変な作業になりました・・・）

バグ情報は、有り難いのですが、状況を出来るだけ詳しく、省略しないで御連絡ください。
COMデバイスなどの場合、ハードウェアが環境により相当異なると思うのですが・・・

**Comment by akirawk** [comment]
管理者権限のみに不都合が生じるというケースは想定していませんでした。失礼しました。通常でも管理者権限でも変化はありません。（他のソフトで管理者権限でなければ通信負荷という事象が出る経験がありましたので、まぁそこで管理者権限で実行してみて変化はありませんか？というやり取りが発生する可能性が出ると思い、それを除外する為に記しました。）

あとは、他に事例が上がってないかを知れれば一度目の問い合わせについてはそれで良かったので情報を揃えるにもコストがかかりますし先の内容に落ち着いた次第です。

フロー制御についてですが、ハード・ソフトともにOFFの状態にしております。受信は出来ています。送信ができてないように見受けられます。（ロジアナで観測まではしていませんという意味で）対向はFTDIのUSB/シリアル変換モジュールで、送受信とも設定は済んでいて他にも記していますが、PC及び対向及びケーブルで他の通信ソフトで使用実績はある環境です。

あれから新たにわかったことがあります。執拗に入力をくりかえしていると、数秒遅延して少しづつ送信しているようです。入力の抜けはあります。

追加の情報としては、PCはLenovo Yoga Book windows版、このPCはUSBホストではないので、OTGケーブルを使用して通常はシリアル通信を日常的に業務で使用しています。

ハード固有のことかもしれませんし、事例の一つとして留めて頂いて結構です。

**Comment by kmiya-culti** [comment]
> FTDIのUSB/シリアル変換モジュール
> 数秒遅延して少しづつ送信しているようです

以上の状況から問題点の特定が出来そうです。FTDIのドライバーでは、CommEventでハードウェアの状態取得がうまく動作していなさそうです。「数秒遅延」は、問題があった場合の救済処理で送信を行っていると思われます。

当方で確認が難しい事例ですが、手持ちのProlificのUSBシリアル変換がWin10でサポートされなくなったのでFTDIのを買ってみようかと思います。

ご報告有り難うございました。
