### ISSUE TITLE
SSH認証鍵ファイル名に$が含まれると読み込まれない

### ISSUE THREAD

**Issue by sus-usu** [kmiya-culti/RLogin#20]
サーバ設定にて、パスフレーズの無いSSH認証鍵ファイル名を例えば「hoge$fuga-moge.key」として登録。
これで接続すると、パスフレーズ入力画面が表示され、鍵ファイル名は「hoge-moge.key」となる。

**Comment by kmiya-culti** [comment]
2.23.4から「UserNameの環境変数展開を削除して特殊文字に併合」の影響です。
「hoge$$fuga-moge.key」で対処をお願いします。

2.23.3で「User Nameに$XXXで環境変数を展開するように変更」の「＄」を残したのが原因です。
どうしようかと思った部分なのですが、マニュアルに記載していませんでした。

そのまま残すか削除するか検討したほうがよさそうですね・・・

**Comment by sus-usu** [comment]
$$でエスケープ出来るのであれば構いません！
おそらく「環境変数で動的に設定出来て助かった」というケースの方が多いのでは？と思います。

当issueはクローズさせていただきます。
お騒がせいたしました！
