### ISSUE TITLE
Sixelの色情報を拡張2

### ISSUE THREAD

**Issue by kmiya-culti** [kmiya-culti/RLogin#22]
Sixelの色情報を拡張する案

目的：Sixelで表現できる色数が端末の文字や背景などで表現出来る色数より少ない為に起こる背景色の不一致などを改善する為。

- 現状：SixelのDECGCI(#Pc;Pu;Px;Py;Pz)

```
Pu=1 : HLS (Px=0-360;Py=0-100;Pz=0-100)
Pu=2 : RGB (Px=0-100;Py=0-100;Pz=0-100)
```

- 拡張案

DECGCIにPu=3でR8G8B8の色空間を追加する。
```
Pu=3 : R8G8B8(Px=0-255;Py=0-255;Pz=0-255)
```

- オプション1

DECGCIに不透明度を指定するアルファ値(Pa)を追加する
```
Pu : 1=HLS(Pa=0-100). 2=RGB(Pa=0-100), 3=R8G8B8(Pa=0-255)
Px;Py;Pz;Pa : Paは、省略可能とし省略値は、最大値とし不透明とする。

※Pa=0の場合には、描画を行わないことで透明を解釈可能
```

- オプション2

 
Sixelに新コマンドRLGCIMAX(*Pu;Px;Py;Pz;Pa)を追加してDECGCIのPx;Py;Pz;Paパラメータの最大値を一時的に変更する
```
Pu : 1=HLS, 2=RGB, 3=R8G8B8(最大値を変更する色空間番号）
Px;Py;Pz;Pa : 各最大値(1-65535), 0の場合は、各色空間のデフォルト値(HLSの場合は、360;100;100;100)

※R10G10B10の場合は(*3;1023;1023;1023)で表現可能。実際の色数は、各端末に依存。
```

**Comment by kmiya-culti** [comment]
オプション２については、たしかに冗長のような気がしましたがメリットも無いことは無いのでオプションで記述しました。

[http://nanno.dip.jp/softlib/man/rlogin/sixel.tar.gz](http://nanno.dip.jp/softlib/man/rlogin/sixel.tar.gz)を更新してRGBのビット数指定-b[bits] とRGBA個別最大値指定-m[r,g,b,a]を実装してみました。どちらも同じオプション２を設定するオプションです。

オプション２があると細かな指定が可能になるので、悪くないと思いましたが、実験以上の効果は、疑問かもしれませんでした。案から削除の方向ですね。

オプション１については、どうでしょう？拡張案に組み込むかオプション扱いのままにするかくらいでしょうか・・・

**Comment by arakiken** [comment]
オプション１については、(今のところmltermでは透過か不透過かの2択でしか扱えませんが)拡張案に組み込んでいただいて支障ないと思います。

オプション2については、新規のコマンド形式を追加するのは抵抗がありますが、当初提案のあった#n;9;r;g;b;aのように、既存のコマンドのパラメータの解釈を追加するような形であれば、あってもいいんじゃないかとは思うんですけど、落としどころが難しいですね。
