### ISSUE TITLE
フォントダイアログからスタイル・サイズが変更できない

### ISSUE THREAD

**Issue by 747** [kmiya-culti/RLogin#23]
### バージョン
- RLogin: 2.23.6 (64bit)
- OS: Windows 10 Pro build 1803 (64bit)

### 手順
1. Font Parameter ダイアログを開く
2. `Font` ボタンを押す
3. フォント名・スタイル・サイズを変更する
4. `OK` を押す

### 症状
- フォント名だけが変更され、スタイルとサイズは変更されない
- もう一度フォントダイアログを開いても、スタイルとサイズはデフォルト（`標準`・`10`）に戻っている

**Comment by kmiya-culti** [comment]
Fontボタンで変更できるのが、フォント名だけです。
[各フォントのパラメータ設定](http://nanno.dip.jp/softlib/man/rlogin/#FONTPARA)の記述を修正しました。
ご指摘有り難うございます。

また、フォントの設定方法については、[フォントの設定](http://nanno.dip.jp/softlib/man/rlogin/faq.html#FONTSET)に詳細を記述しています。

**Comment by 747** [comment]
早速ありがとうございます。
無事フォントサイズの変更ができました。お騒がせいたしました。
