### ISSUE TITLE
高DPI環境下でツールバーのアイコンが小さくなる

### ISSUE THREAD

**Issue by estshorter** [kmiya-culti/RLogin#25]
症状はタイトルの通りです。

環境：
- Win 10 1709
- RLogin 2.23.7
- DPI: 200%

スクリーンショットを以下に示します。
![default](https://user-images.githubusercontent.com/1430311/46117251-2be3ab80-c23b-11e8-9dca-268506e65e6e.PNG)

なお、exeファイルを右クリックして出るプロパティの設定から、「高いDPIスケールの動作を上書きします」を「システム」に設定すると直ります。
![2](https://user-images.githubusercontent.com/1430311/46117298-72390a80-c23b-11e8-9698-138773ba3d84.PNG)

**Comment by kmiya-culti** [comment]
「ヘルプ」「ツールバーのカスタマイズ」で画像サイズの設定で変更できますが、ピクセルサイズなのでHiDPIの変更で矛盾が起こります。

同じように「オプション」「スクリーン」のフォントサイズでも問題がありますが、「フォントサイズ注意」でごまかしています。

「HiDPIの変更でフォントサイズを追従して・・・」がチェックされているとツールバーなどの画像サイズも追従するのが良いかもしれませんね・・・

ご報告有り難うございました。
