### ISSUE TITLE
トリプルクリックによる行全体の範囲選択

### ISSUE THREAD

**Issue by k2hiro** [kmiya-culti/RLogin#28]
最近puttyから乗り換え、大変満足しております。すばらしいツールをありがとうございます。
機能リクエストを上げさせていただきます。

現状マウスのダブルクリックで単語の範囲選択が出来ますが、トリプルクリックによる行全体の範囲選択も対応いただけるとありがたいです。
TeraTerm や putty では対応していますので、これらのソフトから乗り換えたユーザにもうれしいかと思います。

ご検討よろしくお願いします。<(_ _)>

**Comment by kmiya-culti** [comment]
前にも同じ要望があったのですが、現状の仕様と相性が悪いので実装しませんでした。

http://nanno.dip.jp/softlib/man/rlogin/faq.html#LCLICK

**Comment by k2hiro** [comment]
お返事ありがとうございました。
SHIFT + マウスドラッグでも行選択できることが分かりました。
慣れるとこちらの方が使いやすそうです。
ありがとうございました。
