### ISSUE TITLE
RLogin.ini のデコードは可能でしょうか？

### ISSUE THREAD

**Issue by MasaGon** [kmiya-culti/RLogin#3]
PC環境を移設した際に公開鍵置き場のパスが変わってしまいました。接続情報を一括してリプレースし、再インポートしたいのですが、RLogin.ini が暗号化されていてそのままでは編集が出来ません。

RLogin.iniの暗号化を一旦解除して、編集後に再暗号化する方法はありますか？

**Comment by kmiya-culti** [comment]
RLogin.iniのプライベートプロファイルは、直接編集出来るような形式では、ありません。（暗号では、ありません。符号化が正しい表現ですね）

プライベートプロファイルを別のパソコンに移動することは、問題ありません。ファイルのパスなどは、移動後に個別で再設定してください。また、保存されているパスワードなどは、削除される場合がありますのでこれも再設定が必要です。

ちなみに、Server Selectの右クリックメニューで選択できる「ファイルにエキスポート」は、テキストエディタで直接編集できる形式で保存されます。

**Comment by MasaGon** [comment]
なるほど、承知しました。
将来的な希望としてご検討頂ければ幸いです。
