### ISSUE TITLE
サーバ名/ポート/ユーザ名/パスワード(パスフレーズ)を入力する欄の初期フォーカスの位置について

### ISSUE THREAD

**Issue by yasuhirokimura** [kmiya-culti/RLogin#31]
「ファイル」→「サーバに接続」を選択して、「Server Select」で接続先を選択すると、サーバ名/ポート/ユーザ名/パスワード(パスフレーズ)を入力するダイアログが表示されますが、2.24.0まではダイアログが表示された直後のフォーカスはパスワード(パスフレーズ)の欄にありました。そのためそのままパスワードを入力することが出来ました。ところが2.24.1ではフォーカスがサーバ名の欄にあるようになってしまいました。通常この欄でサーバ名/ポート/ユーザ名を変更することは稀だと思うので、2.24.0までのようにフォーカスがパスワード(パスフレーズ)の欄にあるように戻していただけないでしょうか。

**Comment by kmiya-culti** [comment]
確認できました。2.24.1での変更でミスがありました。
次回バージョンで修正します。有り難うございました。

http://nanno.dip.jp/softlib/rlogin/2.24.2/
