### ISSUE TITLE
"Server Select" ダイアログが表示されるたびに大きくなる

### ISSUE THREAD

**Issue by bmtsstl** [kmiya-culti/RLogin#32]
"Server Select" ダイアログのサイズが表示されるたびに大きくなります。プログラムを再起動しても、大きくなったサイズが復元されてしまい、直りません。

# 環境
 - Windows 10 (バージョン 1809, OS ビルド 17763.316)
 - ディスプレイ 1920 * 1200, 表示スケール 150% (HiDPI)
 - RLogin 2.24.1 (2.24.0 では再現しません)

# GIF 動画
![rlogin](https://user-images.githubusercontent.com/35141868/53675752-ed1bbb00-3cdc-11e9-9e45-1ab1378bfc63.gif)

**Comment by kmiya-culti** [comment]
確認できました。2.24.1での変更でミスがありました。
次回バージョンで修正します。有り難うございました。

http://nanno.dip.jp/softlib/rlogin/2.24.2/
