### ISSUE TITLE
要望：接続先を選択するダイアログのエントリの順番を編集可能にしてほしい

### ISSUE THREAD

**Issue by yasuhirokimura** [kmiya-culti/RLogin#33]
「ファイル」→「サーバーに接続」で表示されるダイアログでは、エントリがある順番(エントリ名のアルファベット順？)で表示されますが、この順番をユーザが編集することを可能にしていただけないでしょうか。

要望の背景としては、現在接続先として数十個のエントリが登録されているのですが、それらの使用頻度に

* ほぼ毎日接続する
* 二〜三日に一度は接続する
* 一月に片手程度の回数は接続する
* 接続するのはメンテナンスやトラブル対応の時だけ

のように差があるため、使用頻度の高い順にエントリを並べたい、というのがあります。

何卒よろしくご検討下さい。

**Comment by kmiya-culti** [comment]
次回バージョンからServer SelectにLastとIndexを追加してみました。
どちらもデフォルトでサイズ０にしていますのでヘッダーをサイズ変更しないと見えません。

Lastは、最終アクセス日時でIndexは、エントリーをマウスで移動もしくは、Ctrl+UP/DOWNで移動した順位を記録します。並び替えは、ヘッダーをクリックで昇順・降順（デフォルトは、エントリー名）です。

http://nanno.dip.jp/softlib/rlogin/2.24.2/

![image](https://user-images.githubusercontent.com/30512617/54963573-95efca00-4fac-11e9-992d-3da6fdf3baae.png)
