### ISSUE TITLE
起動時にエラーダイアログが出る

### ISSUE THREAD

**Issue by b-51** [kmiya-culti/RLogin#34]
RLogin 2.24.2（前バージョンから）
Windows 10 Home 1803

いつも便利に使わせていただいております。
契機はちょっとわからないのですが、起動時に「Pane Init Error 'CBuffer GetStr'」というエラーダイアログが出るようになってしまいました。
最近いじったことと言えば、サーバの登録をいくつか増やした（タブも増やした）くらいですので、これが原因かもしれませんが。

![capture](https://user-images.githubusercontent.com/49141513/55369248-b251b080-5530-11e9-86e9-9efc18fcde36.png)

OKを押せば普通に使えますのであまり実害はないのですが、お手すきのときにでもご確認いただければ。
よろしくおねがいします。

**Comment by kmiya-culti** [comment]
それは、メニュー・ウィンドウ・現在の分割を保存で使用するデータが壊れていると思います。

原因の特定が出来れば良いのですが・・・・

**Comment by b-51** [comment]
御返事ありがとうございます。
「現在の分割を保存」をやり直してみたらエラーが出なくなりました。
どうやらそのデータが壊れていたようです。
なぜ壊れてしまったのかは不明ですが、とりあえず解決しました。
お騒がせしました。
