### ISSUE TITLE
コンパイルエラー

### ISSUE THREAD

**Issue by cbdalian** [kmiya-culti/RLogin#37]
このプロジェクトをコンパイルしたいですが、いろなエラーが発生しています。コンパイル環境の設定を教えていただけませんか？
エラーは下記です。
E1696	ソース ファイルを開けません "afxwin.h"
E1696	ソース ファイルを開けません "openssl/des.h"
・・・

**Comment by kmiya-culti** [comment]
僕が使用しているのは「Microsoft Visual Studio 2010」です。
afxwin.hは、たぶんMFCのインストールされていないからでは、ないでしょうか？

openssl/des.hなどは、下記を参照ください・・・
https://kmiya-culti.github.io/RLogin/#COMPILE

**Comment by cbdalian** [comment]
ありがとうございます。試してみます。
