### ISSUE TITLE
[BUG]エントリエクスポート/インポートにpipeプロトコルが未対応

### ISSUE THREAD

**Issue by kanatech** [kmiya-culti/RLogin#39]
### バージョン
-Windows10 x64
-RLogin 2.24.5
### 再現手順
1. サーバエントリ内のプロトコル設定に "pipe" を指定
2. エントリをrlgファイルにエクスポート
3. rlgファイル内の "Entry.Protocol"設定 が "direct"として保存される
### 内容 
エントリ内プロトコル設定の名前-値の対応欠落
CServerEntry::GetProtoName()
CServerEntry::GetProtoType()

**Comment by kmiya-culti** [comment]
確認出来ました。次回バージョンで修正したいと思います。
ご報告有り難うございました。
