### ISSUE TITLE
ライセンスについて提案

### ISSUE THREAD

**Issue by hidekuro** [kmiya-culti/RLogin#4]
> 1.7 RLoginの使用に関して
> --
> RLoginの使用について個人・商用を問わずご自由に使用していただいで結構です。
> また、配布・転載・紹介もご連絡の必要もありません。
> ソースの改変による配布も自由ですが、どのバージョンの改変かを明記されることを希望します。
> また、ソースコードの部分使用なども自由です。

とのことですが、GitHubで LICENSE の明示がないリポジトリは [No License](https://choosealicense.com/no-license/) が適用されます。

No Licenseでは、改変や、別のライセンスを課すと言ったことが禁止されると思います。
（GitHubの利用規約により、ソースの表示とフォークは許可されますが、改変や再頒布は出来ません）

No License の内容に関する参考：
[オープンソース・ライセンスの談話室](http://www.catch.jp/oss-license/2013/09/10/github/)

**_"1.7 RLoginの使用に関して"_** に近しいライセンスを適用するならば、 [Apache License 2.0](https://choosealicense.com/licenses/apache-2.0/) または [The MIT License](https://choosealicense.com/licenses/mit/) とするのはいかがでしょうか。

**_"ソースの改変による配布も自由ですが、どのバージョンの改変かを明記されることを希望します。"_** とのことなので、Apache License 2.0が合致しているかなと思います。（MIT Licenseは変更点の明示を要求しません）

**Comment by kmiya-culti** [comment]
ご提案ありがとうございます。
MITライセンスを明示するようにしてみました。
