### ISSUE TITLE
[要望]クイック接続機能の追加

### ISSUE THREAD

**Issue by kanatech** [kmiya-culti/RLogin#40]
事前にエントリを登録しなくても、最低限の接続パラメータのみで接続できる「クイック接続」のような機能が欲しいです。
FileZillaのようにツールバーに実装されているとなお嬉しいです。

**Comment by kanatech** [comment]
お恥ずかしながら上記の機能に気づきませんでした。
プロトコルごとにエントリを作成しておけば、ほぼ期待通りのことができそうです。
ただ、タイムアウトのプログレスが少々気になります。外すことはできるのでしょうか？

ちなみにFileZillaのツールバー(クイック接続)実装画像をご参考まで
![FileZilla_Quick](https://user-images.githubusercontent.com/49782028/66630487-5c786680-ec3f-11e9-85d7-5873d1826470.png)

個人的には、URL形式([login|telnet|ssh]://user:pass@host:port/file) の一つのみパラメータとして入力できれば十分かと思います。
気が向きましたらツールバー実装についてもご検討いただけますと幸いです。

**Comment by kmiya-culti** [comment]
次回バージョンにクィックバーを追加してみました。
メニュー・表示・クィックバーで表示・非表示します。

http://nanno.dip.jp/softlib/rlogin/2.24.7/

![QuickBar](https://user-images.githubusercontent.com/30512617/70760726-ed79d400-1d8d-11ea-8695-e66b771014aa.jpg)
