### ISSUE TITLE
[質問]コマンドラインからrlgファイルのインポートのみはできますか？

### ISSUE THREAD

**Issue by kanatech** [kmiya-culti/RLogin#41]
[要望]としたかったのですが、できるかもしれなかったので[質問]とさせていただきました。

複数台のPCにRLogin環境をデプロイしたいと考えています。その際、予め幾つかのサーバエントリも登録済みの状態にしておきたいのですが、現在はユーザにGUIからrlgファイルのインポート作業を最初にしてもらっています。

コマンドラインからrlgファイルのインポートのみ(UIは起動せず)行えれば、環境のデプロイが自動化できると考えています。
当該の機能がなければ要望としてご検討いただければ幸いです。

**Comment by KonishiYuzo** [comment]
通りすがりに失礼します。
RLogin.ini ファイルを配置すれば、みなさん同じになります。
私のところでは、それを配って、環境構築してもらっています。
もしくは、セットアップ済みのRLoginをディレクトリごとzipで固めて、配布するとか

**Comment by kmiya-culti** [comment]
2.24.7より起動時にサーバーエントリーが無い場合に実行・作業フォルダにRLogin.rlgがあると読み込みを確認するようにしてみました。ご要望の動作と違いますが、ひな形として利用できます。
