### ISSUE TITLE
(2.24.7) 全角文字の表示位置がずれる

### ISSUE THREAD

**Issue by tesurijp** [kmiya-culti/RLogin#43]
2.24.7 で入った「固定幅フォントの全角文字でも表示幅を調整するように変更」の影響だと思いますが、MS ゴシック指定の場合に、全角文字の幅が半角文字と同じになってしまって表示がずれるようになっています。(2.24.6まででは問題がありません)

MS UI Gothicでは、2.24.7も2.24.6も表示位置は差異はありません。(動作が非常に遅くなるので、常用しづらいですが)

**Comment by kmiya-culti** [comment]
残念ながら状況が確認できません。ご使用の環境や設定および「表示がずれるようになっています」状態の画像などがあれば助かります。

**Comment by tesurijp** [comment]
表示のずれは、以下のような形になっています。
2.24.6
![Clipboard01](https://user-images.githubusercontent.com/8403496/70955013-b6b7fc80-20b2-11ea-9ad1-394c91765f5f.png)
2.24.7
![Clipboard02](https://user-images.githubusercontent.com/8403496/70955025-bd467400-20b2-11ea-98ac-fb4720ea4082.png)

ホスト側のエンコードはUTF-8です。
Rloginの設定で、関連するのは以下のページだと思いますので、あげておきます
![setting](https://user-images.githubusercontent.com/8403496/70955166-3776f880-20b3-11ea-9066-5412b56fade2.png)

**Comment by kmiya-culti** [comment]
UTF-8の場合にオプション・制御コード「8449 文字幅の調整をしない」場合に上記の状態になることを確認しました。8449をオフでお試しくだされば幸いです。

今回の「固定幅フォントの全角文字でも表示幅を調整するように変更」が影響しているのですが元に戻すのは、絵文字などの場合に問題があるので方法を考えてみます。

ご報告有り難うございました。

**Comment by tesurijp** [comment]
8449 オフで、解決しました。
ありがとうございます。
