### ISSUE TITLE
ロリポップレンタルサーバに対してSSH接続ができない

### ISSUE THREAD

**Issue by aglarms** [kmiya-culti/RLogin#44]
### バージョン

Windows10 (1903)
Rlogin: 2.24.6(x64)
設定はRlogin.iniに保存

### 再現手順

1. "Server Edit Entry" ダイアログで、以下のように設定して保存。
これ以外の設定はデフォルトから変更していない。
--
エントリー（上）：lolipop
プロトコル：ssh
ホスト名：ssh.lolipop.jp
TCPポート：2222
ログインユーザー名：lolipop.jp-dp0000000 (←0の部分は数字7桁のユーザーID)
パスワード：空欄
デフォルト文字セット：UTF-8
--
1. "Server Select" ダイアログで、1で保存した設定を選択した状態でOKボタンを押して接続しようとすると、直後に接続が切れてしまう。

![lolipop](https://user-images.githubusercontent.com/39684380/70913201-e5a18480-2058-11ea-8ab1-c29391cf705c.gif)

### 内容

通常であればOKボタンを押したあとに、ホストの公開鍵情報が表示されますが、それも表示されず、なんのダイアログも表示されないまま一瞬で接続が切れてしまいます。

同じPCからTeraTerm、PuTTY、Windowsのターミナルを使っての接続は問題なく完了できたので、ロリポップサーバー側の問題ではないように思います。

どうにも不可解で、解決方法の見当がつきません。
ググってもみたのですが、おそらく自分と同じ状況にある人を一人発見できただけでした→
https://mevius.5ch.net/test/read.cgi/hosting/1464370403/236

原因、または追加で設定すべき項目に心当たりがありましたらご教示ください。

**Comment by kmiya-culti** [comment]
「パスワード：空欄」がパスワードを接続時に入力したいと云う意味ならば、オプション・サーバー「ホスト・ポート・ユーザー・パスワード／フレーズを接続時に入力」をチェックしないとパスワード無しで接続しようとします。

また、オプション・通信共通の「接続が切れてもウィンドウを閉じない」をチェックするとなんらかのエラー表示などを確認することができます。

**Comment by aglarms** [comment]
申し訳ありません、説明が不十分でした。
「パスワードを接続時に入力したい」のは間違いないのですが、今までロリポップ以外のサーバに接続するときは、パスワードは空欄にして「ホスト・ポート・ユーザー・パスワード／フレーズを接続時に入力」のチェックをオフのまま接続していました。
その場合は、以下のような流れで接続できていたので、今回もそのように設定していました。

1. "Server Select" ダイアログで、サーバを選んでOKを押す
1. 初めて接続するサーバであれば、"公開鍵の確認" ダイアログが表示され、公開鍵情報が表示される
2. "公開鍵の確認" ダイアログの「接続する」ボタンをクリックする
3. "パスワード/パスフレーズ入力" のダイアログが表示される
4. パスワードを入力してOKボタンを押す
5. 接続完了

ロリポップに接続しようとした場合、2番にたどり着けずに切断されてしまうので、公開鍵の受け取り、またはそれ以前の段階で問題が発生しているのでは？と思いました。


とりあえず、いただいたコメントを参考にして、以下の2つの設定で接続を試してみました。
記載のない設定は、最初に書き込んだものから変更していません。

#### 設定１

* パスワード：空欄
* 「ホスト・ポート・ユーザー・パスワード／フレーズを接続時に入力」：オン
* 「接続が切れてもウィンドウを閉じない」：オン

結果
"Server Select" ダイアログでサーバを選んでOKを押すと、"ssh.lolipop.jp" というダイアログが表示されるので、パスワードを入力してOKボタンを押す。
直後にウインドウに「closed」と表示される。他にエラー、ダイアログ等は表示されない。


#### 設定２

* パスワード：ロリポップのSSH用パスワードを入力
* 「ホスト・ポート・ユーザー・パスワード／フレーズを接続時に入力」：オフ
* 「接続が切れてもウィンドウを閉じない」：オン

結果
"Server Select" ダイアログでサーバを選んでOKを押すと、直後にウインドウに「closed」と表示される。他にエラー、ダイアログ等は表示されない。

以上です。
特定のレンタルサーバサービスでのみ発生している現象なので、検証を行うのは難しいかと思いますが…どうぞよろしくお願いいたします。

**Comment by kmiya-culti** [comment]
ロリポップのお試しが利用出来たので確認してみました。どうも暗号化方式のchacha20-poly1305@openssh.comが正しく動作していないようです。オプション・プロトコル・暗号化方式で入出力を変更する必要があるようです。

次回バージョンでchacha20-poly1305@openssh.comの優先順位を下げてみようかと思います。

![ssh](https://user-images.githubusercontent.com/30512617/71049119-d9b2e100-2184-11ea-9a79-b6fd39da8b38.jpg)

**Comment by aglarms** [comment]
指示の通り、暗号化方式で chacha20-poly1305@openssh.com の優先度を下げたところ、無事に接続できました！
鍵交換周辺の設定は、不勉強ゆえ思い当たりませんでした。TeraTermの設定画面と見比べてみたら、たしかに優先順位が違っていました。

お試し登録までしていただいて、大変お手数をおかけいたしました。
この件はクローズいたします。ありがとうございました。
