### ISSUE TITLE
実行プログラムが 32bit 版/64bit 版のどちらなのかを [RLoginのバージョン情報] に明記して欲しい

### ISSUE THREAD

**Issue by msmhrt** [kmiya-culti/RLogin#46]
一点要望です。

Windows 10 Home で RLogin Version 2.24.7 (2019/12/16) を使用しているのですが、自分が使用中の RLogin が 32bit 版なのかそれとも 64 bit 版なのかを確認したくなることがたまにあります。

[RLoginのバージョン情報] にはこの情報が書かれていないようなのですが、明記することを検討していただけないでしょうか？

もし、私が見逃しているだけで実は書いてある、あるいは他の箇所に書いてあるとかでしたら、すみません。

**Comment by kmiya-culti** [comment]
次回バージョンで下記のように表記してみます。

![image](https://user-images.githubusercontent.com/30512617/72483685-39181580-3845-11ea-99f0-54788ddc66d4.png)

**Comment by msmhrt** [comment]
対応ありがとうございました。

32 bit 版で「(x86)」と表記（ですよね？）すると、意図が分からなかったり ARM 版と Intel CPU 版の 2 種類があると誤解してしまう人もいるのでは？と少し心配になったのですが、RLogin を使うような人なら多分大丈夫ですよね。
