### ISSUE TITLE
機能要望 - Windwsのスリープ抑制(電源管理)機能

### ISSUE THREAD

**Issue by Xanardi** [kmiya-culti/RLogin#47]
ホスト側で時間の掛かる処理を行ってる最中，端末を放置しているとスリープしてセッションが切れてしまい，結果としてホスト側で実行していた処理がエラーになってしまう。
セッション確率中はスリープを抑制するための機能が欲しいです。
(スクリーンロックやディスプレイオフは問題ないのですが...)

**Comment by kmiya-culti** [comment]
オプションにしようかと思いましたが、接続中のスリープで切断されても大丈夫な状況が考えにくいですね・・・

次回バージョンにスリープを抑制するようにしてみました。お試しいただければ幸いです。

http://nanno.dip.jp/softlib/rlogin/2.25.0/

**Comment by ttdoda** [comment]
* WSL
 * Cygwin
 * ローカルのVM上のサーバ

辺りはスリープしても切れないし、自分がスリープしている時は相手もスリープしているので、スリープして欲しいかも。

あと、サーバ側でscreenやtmuxを使っていて切れても再接続すればいい時も設定どおりスリープして欲しい場合も有ると思います。

**Comment by Xanardi** [comment]
ありがとうございます。スリープ抑制は機能してるようです。
スリープ抑制の有効/無効切り替えが必要かどうかは，私の使い方ではなんとも言えないのですが。

**Comment by kmiya-culti** [comment]
スリープによる接続切れは、なかなか深い問題のようですね・・・どうもサーバーからの送信エラーによるタイムアウトとルーターなどのNATタイムアウトが怪しいようです。スリープでTCPのコネクションを切っていることは、無いようですね。

オプションにする場合は・・・

1.何もしない（現状）
2.送信・受信が指定時間無い場合はスリープする（ファイル転送時などは、スリープを抑制）
3.接続中は、スリープしない

が考えられますね・・・デフォルトは２かな？

**Comment by kmiya-culti** [comment]
早速、オプションとして実装してみました。ファイル転送時などは、スリープに移行しないほうが良さそうなのでデフォルトは、Activeにしました。

http://nanno.dip.jp/softlib/man/rlogin/#SCREENOPT
http://nanno.dip.jp/softlib/rlogin/2.25.0/
