### ISSUE TITLE
レンダリングのイベントハンドルバグ(?)

### ISSUE THREAD

**Issue by Xanardi** [kmiya-culti/RLogin#48]
タブ(セッション)を複数開いた状態にし，非アクティブなタブ上にマウスカーソルを移動させて数秒待つと，スクリーンのレンダリングがアクティブ・非アクティブの内容がブレンド(高速スイッチ?)され，おかしくなる。
透明度の設定は関係ないようです。

**Comment by kmiya-culti** [comment]
それは、仕様です。動作を変更することもできます。

http://nanno.dip.jp/softlib/man/rlogin/#WINDOW
http://nanno.dip.jp/softlib/man/rlogin/#MOUSEOPT

**Comment by Xanardi** [comment]
ユニークな機能だったので勘違いしてました。ありがとうございます。
