### ISSUE TITLE
文字コード 000 の送信設定

### ISSUE THREAD

**Issue by arthurm** [kmiya-culti/RLogin#49]
バージョン情報: RLogin (x64) Version 2.24.9 (2020/02/24)

emacs の set-mark-command が標準で割り当てられているキーシーケーンス Ctrl + SPACE は、文字コード \000 を送信する必要があります。これは設定の「キーボード」の「キーコード」で、Code=SPACE, With=Ctrl の行に対してString=\000を設定することで実現されることが期待されます。

サーバに接続後、「表示」メニューの「オプション設定」の「キーボード」から設定した場合、設定画面上は何も表示されないものの、実際に Ctrl + SPACE で \000 が送信されています(emacs の set-mark-command が動作します)。しかし、接続設定の該当部分を設定して保存し、それを使用して接続した場合にはうまくいきません。したがって、サーバに接続するたびに上記オプション設定を行う必要があります。

・このオプション設定が表示上も正しく残る
・接続設定にて設定した場合にも正しく保存され有効となる

よう改善いただけるとありがたいです。

**Comment by kmiya-culti** [comment]
次回バージョンで修正します。

http://nanno.dip.jp/softlib/man/rlogin/#HISTORY
