### ISSUE TITLE
[BUG]SSHにて名称の長いディレクトリにcdすると操作ができなくなる

### ISSUE THREAD

**Issue by odasusu** [kmiya-culti/RLogin#5]
## バージョン

- CentOS 7.4
- Window 7 x64 Windows 10 x64
- RLogin 2.22.8

## 再現手順

1. メニューからタブバーを表示
2. CentOSへSSHにてログイン
3. 名称が255バイト有るディレクトリへcd

## 内容

- SSHにて長いディレクトリにcdすると画面上部のタブが点滅して該当タブの操作ができなくなる。
- 該当タブ以外の操作は可能。
- 複数のホストにて現象を確認。
- タブバーを表示しなければ発生しませんでした。

**Comment by kmiya-culti** [comment]
ご報告ありがとうございます。
確認できました。次回バージョンで修正しようと思います。
