### ISSUE TITLE
Unable to build : libiconv1.15

### ISSUE THREAD

**Issue by pseudorandomID** [kmiya-culti/RLogin#50]
I tried to build Rlogin project so that I can modify it for my own use.
However, I couldn't make libiconv1.15. 
The instruction you gave on "https://kmiya-culti.github.io/RLogin/" is not vaild now.

'nmake -f Makefile.ms x64'
I tried to run this command but there is no such file like Makefile.ms.

How can I set up environment with libiconv1.15?

**Comment by kmiya-culti** [comment]
下記のパッチにMakefile.msが含まれています
===
Makefile.ms is included in the patch below

http://nanno.dip.jp/softlib/man/rlogin/libiconv-1.15.patch

**Comment by pseudorandomID** [comment]
> 
> 
> 下記のパッチにMakefile.msが含まれています
> Makefile.ms is included in the patch below
> 
> http://nanno.dip.jp/softlib/man/rlogin/libiconv-1.15.patch

It worked perfectly,
Thanks.
