### ISSUE TITLE
Creates duplicate entry in Termnames

### ISSUE THREAD

**Issue by pseudorandomID** [kmiya-culti/RLogin#53]
Creates duplicate entry in Termnames

_Originally posted by @pseudorandomID in https://github.com/kmiya-culti/RLogin/pull/52_

This is the bug that I've already mentioned (please refer to the link above).

As you can see from the link, I fixed it by removing two lines.
I wonder if this fix violates any of coding convention of the project or breaks the architecture of the program.

If this fix is allowed, I would like to create a pull request with my fix.

**Comment by kmiya-culti** [comment]
修正したつもりでいましたが、2.25.1のバージョンに入れ忘れました。
ご報告有り難うございます。
-- --
I intended to fix it, but I forgot to put it in the 2.25.1 version.
Thank you for your report.
