### ISSUE TITLE
【要望】ペーストする際、『指定された文字が含まれていたら』クリップボードから確認するようにしたい

### ISSUE THREAD

**Issue by ShotaAnda** [kmiya-culti/RLogin#54]
昨年からRloginを利用しているのですが、1点対応可能か要望させてください。

ペーストした時、『常にクリップボードからペーストするテキストを確認する』にチェックを入れることでクリップボードが毎回開いてくれるようになりますが、
それをペースト内に特定の文字が含まれていたらクリップボードを開くようにできますでしょうか？

背景としては改行コードが含まれる時にだけクリップボードで中身を確認したく、
それ以外の場合はそのままペーストしたいという要望となります。

こちらご確認いただけますでしょうか？

**Comment by kmiya-culti** [comment]
「常に」でない通常ですね・・・

http://nanno.dip.jp/softlib/man/rlogin/#CLIPOPT

常にクリップボード…
通常は、複数行やコントロールコードが含まれる場合に表示されるペースト確認・編集ダイアログを常に表示します

**Comment by ShotaAnda** [comment]
すみません。。。
『常にクリップボードからペーストするテキストを確認する』にチェックを入れていない場合は改行コードを含む場合のみクリップボードが表示されるようになるのですね…

確認不足でお手数おかけしてしまい申し訳ありませんでした
