### ISSUE TITLE
Windows 10 May 2020 Update で RLogin が起動できない

### ISSUE THREAD

**Issue by iwanee** [kmiya-culti/RLogin#55]
■現象
Windows Update 後、RLogin を起動すると、一瞬起動するものの、そのままウィンドウがすぐに強制終了して落ちてしまう。
エラーメッセージは特に表示されませんでした。

■環境
使用バージョン: rlogin 2.25.2
クライアント環境: Windows 10 64-bit (May 2020 Update)

**Comment by kmiya-culti** [comment]
当方のWindows 10をバージョン2004にしてみましたが、症状が出ませんでした。
なにか条件があるようです。広く情報がいただければ幸いです。

**Comment by sayiwai** [comment]
あれから特に何もしていませんが、現在は正常に起動し、利用できるようになっています。
デフォルトから変えている部分は ini ファイルを別途用意しているぐらいですが、現在起動できることからソフトウェア側ではなく、クライアント環境側（特にメモリあたり）の問題と推測しています。

ともあれお騒がせしました。
また、ご対応ありがとうございました。

**Comment by iwanee** [comment]
あれから特に何もしていませんが、現在は正常に起動し、利用できるようになっています。
デフォルトから変えている部分は ini ファイルを別途用意しているぐらいですが、現在起動できることからソフトウェア側ではなく、クライアント環境側（特にメモリあたり）の問題と推測しています。

ともあれお騒がせしました。
また、ご対応ありがとうございました。

（RLogin では DB の utf8_general_ci のレコード内のテキストで一部文字化けして表示されたりといったことがありますが、必要に応じて別途ご報告するかもしません。ちなみに mintty では文字化けせずに表示できました。）
