### ISSUE TITLE
Proxy使用時のhostヘッダについて

### ISSUE THREAD

**Issue by zoozoo21** [kmiya-culti/RLogin#58]
SSHで利用しています。　　
proxy経由で接続時に、proxyサーバーから接続が拒否されます。他のSSHクライアントでは接続できているのでHTTPヘッダを比較したところ他のクライアントはhostヘッダに接続先のホストが設定されているのですが、RLoginではproxyサーバーのアドレスが設定されています。　　
これは意図した仕様でしょうか。

**Comment by kmiya-culti** [comment]
2.24.3で変更されていました・・・理由を完全に忘れてしまいました・・・うーん

元のサーバーアドレスに戻してみました。お試しいただければ幸いです。

http://nanno.dip.jp/softlib/rlogin/2.25.5/

**Comment by zoozoo21** [comment]
早急な対応ありがとうございます。


試してみましたが、HOSTヘッダはproxyのままで変わっていないようです。
バージョンは2.25.5bと表示されています。
proxy protocolはHTTP(Basic)、Over SSLは使用しないを選択しています。  
CONNECTメソッドのパケットを確認しています。

**Comment by kmiya-culti** [comment]
ご確認有り難うございます。状況が理解できました。
2.24.3での変更が正しくてHTTP(Basic)の場合に修正が漏れていたようです。
再度、ご確認いただければ幸いです。

http://nanno.dip.jp/softlib/rlogin/2.25.5/

**Comment by zoozoo21** [comment]
ありがとうございます。
接続確認できました。
