### ISSUE TITLE
ローカルプロキシ(SSHのProxyCommand相当)対応について

### ISSUE THREAD

**Issue by Harbie34** [kmiya-culti/RLogin#59]
ホームページの「5.16 SSHによる多段接続」でSOCKSを使用した多段接続方法が説明されていますが、SSHのProxyCommandに相当するローカルプロキシを使う方法はないでしょうか。

AmazonのAWS/EC2へSSH接続する際に、ローカルのバックグラウンドで「aws ssm start-session ～」というコマンドを実行することにより、Session Managerという仕組みを経由して接続することができるようになっています。これを使うとAWS/EC2側で外部にSSHポートを開放せずに接続できるので便利です。
https://docs.aws.amazon.com/ja_jp/systems-manager/latest/userguide/session-manager-getting-started-enable-ssh-connections.html
PuTTYではプロキシの種類として「ローカル」の選択肢があるため、ローカルプロキシコマンドとして上記を指定することができるようになっていました。

AWSのSession Managerを使いたいというのはかなり限定的な用途かとは思いますが、対応方法があれば教えてください。
ネット上にはconnect.exeを使用した多段SSH接続方法が解説されているサイトがありますが、その場合にも同じような仕組みになるのではないかと思います。(SOCKSで多段接続ができるのでRLoginでそれを使うことはなさそうですが…)

環境情報
- Windows 8.1 Pro 6.3.9600
- RLogin x64 2.25.4
- aws-cli 2.0.47
- session-manager-plugin 1.1.61.0

**Comment by kmiya-culti** [comment]
現在のプログラムの構成的には、難しい機能になりますね・・・

かなり前から色々と試しているストリーム的に入出力を自在に構成できるようにすれば、パイプをsshに接続するようなイメージになりますね。これが以外と美しくプログラムが書けないので放置しています・・・うーん

**Comment by Harbie34** [comment]
ご回答ありがとうございます。

泥臭い実装をすると拡張性や保守性が失われるのであまり強く要望するつもりはありません。
あとはこの機能がほしいと思っている潜在ユーザーがどれくらいいるかですね…😅

**Comment by kmiya-culti** [comment]
次回バージョンにプロキシ設定にProxy Commandを指定できるようにする予定です

http://nanno.bf1.jp/softlib/man/rlogin/#HISTORY
http://nanno.bf1.jp/softlib/rlogin/2.28.1/

connect.exeでの動作確認は、できましたが
Session Managerなどでの動作確認をお願いしたいと思っています

**Comment by kmiya-culti** [comment]
早速、お試しいただき有り難うございます。詳細な報告で助かります
修正しましたので再度、お試しいただければ幸いです。

http://nanno.bf1.jp/softlib/rlogin/2.28.1/

**Comment by Harbie34** [comment]
早速ご対応いただきありがとうございます！🙇
ひとまずAWSのSession Managerが使えるようになったことを確認しました。🙌
ただ、ちょっと別の問題(？)が見つかったのでご報告です。

- Proxy Commandの%p展開について
TCPポートが「ssh」になっていると、%pも「22」ではなく「ssh」になってしまうようで、Session Managerがエラーになりました。
TCPポートに「22」を指定しておけば問題ありませんでしたし、%p展開の仕組みを変更するのは影響が大きいかもしれないので、ご対応いただかなくても構いません。

```
An error occurred (InvalidParameters) when calling the StartSession operation: Parameter "portNumber" has value "ssh" not matching "^([1-9]|[1-9][0-9]{1,3}|[1-5][0-9]{4}|6[0-4][0-9]{3}|65[0-4][0-9]{2}|655[0-2][0-9]|6553[0-5])$".
```

- TCPポート入力欄のコンボボックスについて
上記の%pについて何度か試しているときに気付きました。
例えばサーバーAが「22」、サーバーBが「22021」というポート設定にしてある場合、サーバーAの設定画面を開くと「22021」になっているので、そのまま保存すると書き換わってしまいます。
コンボボックスが前方一致検索で選択されている雰囲気でしたのでご確認ください。

- ホスト鍵の更新確認が毎回表示される
Session Manager経由で接続するサーバーの場合、以下の画面で「はい」を選択しても次回接続時にまた表示されます。
![20230324_091055](https://user-images.githubusercontent.com/1227499/227397473-2afdb90d-c2c2-42cf-878e-5cd03d298b04.png)

**Comment by kmiya-culti** [comment]
> TCPポート入力欄のコンボボックスについて

すべてのコンボボックスを完全一致に変更しようと思います

> ホスト鍵の更新確認が毎回表示される

これが問題ですね・・・
現在は、接続したサーバー名：ポート番号で管理しているのですが
単純にエントリー名で管理すると簡単なんですが、同じエントリーで別サーバーに接続した場合に矛盾が起こります
何か良い方法を考えないといけないですね・・・
メニュー・ヘルプ・登録されたホスト鍵の削除で確認できますが、すごく増殖してると思います

**Comment by Harbie34** [comment]
> すべてのコンボボックスを完全一致に変更しようと思います

ありがとうございます。😊

> これが問題ですね・・・ 現在は、接続したサーバー名：ポート番号で管理しているのですが 単純にエントリー名で管理すると簡単なんですが、同じエントリーで別サーバーに接続した場合に矛盾が起こります 何か良い方法を考えないといけないですね・・・ メニュー・ヘルプ・登録されたホスト鍵の削除で確認できますが、すごく増殖してると思います

正式版RLoginとは別のフォルダに置いて試していたので、登録されたホスト鍵をすべて削除してから何度か接続してみましたが、ホスト鍵の更新確認は毎回表示されるものの、特に「増殖してる」雰囲気はなさそうでしたが…？
一部モザイク処理をさせていただきましたが、ホスト名に設定しているのは `i-0～2d` なのに、末尾に `:0` が付いていたのがちょっと気になるところです。

![20230324_112946](https://user-images.githubusercontent.com/1227499/227409133-9eb509b9-cb1e-44a9-96c8-8702603a527f.png)

**Comment by kmiya-culti** [comment]
現在作業中の次期試作版にイージーなバグがありました。
MessageBoxの処理で戻り値を無視してしまう部分があり保存処理してなかったです

ホスト名：ポート番号が接続の度に変わらなければ問題ないはずですね・・・失礼しました
色々と問題が見つかり大変助かりました。有り難うございました

**Comment by Harbie34** [comment]
何度もご対応いただきありがとうございました。
正式リリースを楽しみにしております。😊
