### ISSUE TITLE
[bug]接続時にPageant初回起動確認ダイアログが毎回表示される。

### ISSUE THREAD

**Issue by ksatoksato** [kmiya-culti/RLogin#6]
Ver2.22.4から2.22.8に上書きアップデート実施後、以下の事象が発生しております。

サーバー選択より接続する際に毎回、

「このエントリーで最初のPageantの起動を確認しました
使用する認証鍵の優先順位を設定してください
以後、鍵の追加などした場合に設定が必要になります。」
「はい」、「いいえ」

のダイアログが表示されます。
「はい」を押下で設定し、切断時に設定を保存した場合も、
「いいえ」を押下した場合も、次回接続時に同様にダイアログが表示されます。

対象の接続はパスワード認証を使用しており、鍵認証は使用しておりません。

回避方法がありましたらご教示ください。

**Comment by kmiya-culti** [comment]
Pageantに鍵が登録されていない状態では、確認ダイアログが毎回表示される問題を確認しました。
１つでもPageantに鍵があれば、一度確認して設定を保存すると次回からは、確認しないようになります。

次回バージョンからは、空のPageantでは、確認しないようと変更しようと思います。
ご報告、有り難うございました。
