### ISSUE TITLE
マルチスクリーン時のSFtp画面の表示位置について

### ISSUE THREAD

**Issue by comefigo** [kmiya-culti/RLogin#61]
# 事象
以下の手順でSFtp画面が表示されなくなります。

1. 2画面構成のマルチスクリーン（スクリーン１、２とする）時にスクリーン1にRLogin画面、スクリーン2にSFtp画面を表示します。
2. SFtp画面の「x」で閉じ、RLoginも同様に閉じます。  
　※再度RLoginとSFtpを起動し、それぞれの画面が手順1と同じスクリーンに表示されること。
3. マルチスクリーン構成を解除し、スクリーン１のみとする。
4. SFtpを起動しようとすると表示位置が以前のスクリーン２にあるため、表示されません。

# 環境情報

製品バージョン：2.25.5
OSバージョン：Windows 10 Pro 19041.508
グラフィックボード：Geforce系

**Comment by kmiya-culti** [comment]
状況を確認しました。次回バージョンで修正したいと思います。
ご報告有り難うございました。
