### ISSUE TITLE
要望：ssh認証鍵の登録をhost+portにして欲しい

### ISSUE THREAD

**Issue by KaiShoya** [kmiya-culti/RLogin#62]
下記のようなポートフォワードの設定をしています。（エントリー名：フォワード用サーバ）
Type|Listened Host|Port|Connect Host|Port
--|--|--|--|--
local|localhost|1022|192.168.0.10|22
local|localhost|2022|192.168.0.11|22

前接続先に「フォワード用サーバ」を設定したエントリーを複数作成して使用しているのですが、「サーバ1」に接続した後、「サーバ2」に接続、「サーバ1」に再接続とすると、「このホストの公開鍵を信頼して接続しますか？」とダイアログが表示されます。
エントリー名|ホスト名|TCPポート
--|--|--
サーバ1|localhost|1022
サーバ2|localhost|2022

おそらくlocalhostをキーにして保存しているからだと思うのですが、ホスト名+ポート番号で保存するように変更していただけないでしょうか。

**Comment by kmiya-culti** [comment]
要望としては、理解できますが、複数のホスト鍵（ssh認証鍵？ホスト鍵ですね）を管理するのは、
ホストが行うべきでクライアントでは、ホストが認知しないホスト鍵を別とするのが良いと思います。

今回の場合は、ポートフォワードをLocal Socksにしてプロキシ設定するのが良いと思います。
その場合は、ホスト名とホスト鍵を認識して管理できます。

http://nanno.dip.jp/softlib/man/rlogin/faq.html#SSHCASCADE

**Comment by KaiShoya** [comment]
@kmiya-culti  
Local Socksの使い方間違ってました。

すみません、色々と勘違いしてました。
known_hostsに登録されるやつっぽいのでおそらくホスト鍵ですね。。。

**Comment by KaiShoya** [comment]
@kmiya-culti  
ありがとうございます！
Local Socksを使用して解決しました。

ドキュメントにしっかり書いてありますね。。
お手数をおかけしました。

すみません、勘違いしてました。
known_hostsに登録されるやつっぽいのでホスト鍵の間違いです。

**Comment by ttdoda** [comment]
元の要望の使い方ならばLocal Socksを使う方がいいですが、VirtualBoxで複数のVMを起動していて、

 * VM1: Port 10022 ⇒ Port 22
 * VM2: Port 20022 ⇒ Port 22

みたいな感じにポートフォワーディングの設定をしている場合にはやはりポート毎に分けてホスト鍵を管理して欲しいですね。

OpenSSHもかなり前のバージョンから22以外の時はポート番号付きでknown_hostsのエントリを管理していますし、Tera Termもそうしています。

**Comment by kmiya-culti** [comment]
問題になるのは、RFC 4255のDNSに登録されたホスト鍵のチェックだけかもしれませんね・・・
（DNSでのチェックを無視するオプションの追加でしょうか・・・）

次回バージョンからホスト名＋ポート番号にしてみようかと思います。
