### ISSUE TITLE
通信ログの行頭に時間を記録するフォーマットに%N(ミリ秒)を指定するとアプリケーションが落ちる

### ISSUE THREAD

**Issue by yabeaki** [kmiya-culti/RLogin#63]
HP-UX 11において、SSH2認証後ターミナルが表示されず、しばらくすると(1-2分程度)アプリケーションが落ちます。
このとき、通信ログサイズは0バイトでした。
通信ログ設定において、たまたま接続しターミナルが表示されたため、通信ログのオプションを確認したところ、
RAWにしていました。
そこで、RAW以外のオプションにし、通信ログの行頭に時間を記録するをONにすると落ち、
OFFにすると無事接続できたことを確認しました。
AIXやLinuxでは、RAW以外かつ「通信ログの行頭に時間を記録する」が有効でもを問題なく接続できターミナルが表示されるため、HP-UX独特の制御が入っているのかもしれません。
このオプションは後日ログを見返す際に役に立つことが多いため可能であれば時間が記録できるように修正いただけますと幸いです。
何卒ご検討のほどよろしくお願いいたします。

**Comment by yabeaki** [comment]
HP-UX固有の問題ではなさそうです。
改めて確認したところ、時間記録のフォーマットに「%N」(ミリ秒)を指定すると落ちるようです。
プルダウンにあるデフォルトフォーマットを指定して接続したらうまくいきました。
また、%y(年2桁)→%Y(年4桁)でも問題なく接続できました。
%N(ミリ秒)はサポートされていない感じでしょうか。
※そもそもミリ秒がイレギュラーでしたら申し訳ありません。

**Comment by kmiya-culti** [comment]
現在、使用しているVCでは、”%N”をサポートしていません。
しかしstrftimeでサポートされない文字で強制終了されるのは、良くないですね。

次回バージョンから未サポート文字を無視するようにしてみます。
ご報告有り難うございました。

**Comment by kmiya-culti** [comment]
2.25.7から未サポートフォーマットを無視するようにし%Lでミリ秒を表示するようにしました。

https://github.com/kmiya-culti/RLogin/releases/tag/2.25.7
