### ISSUE TITLE
背景のオプション設定-テキスト描画で、表示する文字列の改行指定が無効になっている

### ISSUE THREAD

**Issue by yabeaki** [kmiya-culti/RLogin#64]
2.25.7から、「\r\n」がそのまま表示され、初期設定の「%E\r\n%S」の場合
サーバー名\r\nIPアドレス
と1行で表示されてしまいます。
2.25.6までは改行が正常に認識されておりました。
ご確認をお願いいたします。

**Comment by kmiya-culti** [comment]
確認いたしました。ご報告有り難うございました。

http://nanno.dip.jp/softlib/rlogin/2.25.8/

**Comment by yabeaki** [comment]
修正後バイナリを作成いただきありがとうございました。
64bit、32bit両方とも背景のテキストの「\r\n」が改行に変換されていることを確認いたしました。
修正ありがとうございました。
正式リリースをお待ちしております。
