### ISSUE TITLE
Feature Request: Connect to unregistered server through quick bar

### ISSUE THREAD

**Issue by byeonlab** [kmiya-culti/RLogin#67]
![image](https://user-images.githubusercontent.com/19143607/113527471-99d17080-95f8-11eb-8bc0-634ec0e35060.png)

Through quick bar, I can only connect to the servers that I registered before.
It would be nice if I can login to unregistered server by only filling host/port, User, pass. (Just like putty)

**Comment by kmiya-culti** [comment]
クィックバーので接続は、ベースとなるエントリーの設定が必要です。
そのエントリーの設定からホスト・ポート・ユーザー名・パスワードをクィックバーで指定した物に置き換わります

--- Automatic translation --
The quick bar connection requires the setting of the base entry.
From the setting of that entry, the host, port, user name and password will be replaced with the one specified in the quick bar.
