### ISSUE TITLE
2行目以降のチャットスクリプトが実行されません

### ISSUE THREAD

**Issue by webspsuzuki** [kmiya-culti/RLogin#68]
Ver.2.25.9.0以降になりますが、「チャットスクリプト」で設定した2行目以降の送信文字列が送信されず、実行できないようです。
1行目が実行されたあと、「Chat Script」のウィンドウの中で「Execute」の表示のままプログレスバーがじわじわ上がって行きます。

**Comment by kmiya-culti** [comment]
残念ながら状況が把握できません。
詳細をお知らせください（動作しないチャットスクリプトなど）
こちらで再現できるだけの情報をお願いいたします。

**Comment by webspsuzuki** [comment]
早々のご対応ありがとうございます。画像を添付します。
![rlogin01](https://user-images.githubusercontent.com/81940622/113544795-eed6ac00-9623-11eb-8e67-19dd6bac01a5.png)
サーバへの接続設定を入れ（一部に画像処理を入れています）、「チャットスクリプト」から
![rlogin02](https://user-images.githubusercontent.com/81940622/113544884-16c60f80-9624-11eb-98e9-ca3f3c47c771.png)
ログ監視開始までを自動化していました。（実際に監視しているログは別のものです）
![rlogin03](https://user-images.githubusercontent.com/81940622/113544890-1a599680-9624-11eb-9ac2-cb201362d480.png)
1行目にtail -f、2行目に改行をたくさん入れて既存ログと区別して、以降発生するログがすぐわかるようにしていたのですが、
![rlogin04](https://user-images.githubusercontent.com/81940622/113544896-1cbbf080-9624-11eb-9aa6-797e46646ce9.png)
ChatScriptのウィンドウが表示されたままになり、2行目以降が実行されていないように思われます。
拙い説明で大変恐縮ですが、いかがでしょうか。

**Comment by kmiya-culti** [comment]
確認できました。
チャットスクリプトで受信文字列が無い場合の処理が正規表現ライブラリを変更したときに間違っていました。

次回バージョンで修正したいと思います。
ご報告ありがとうございました。

**Comment by webspsuzuki** [comment]
ご確認ありがとうございます。
rloginは非常に便利で重宝しています。よろしくお願い致します。

**Comment by kmiya-culti** [comment]
次期試作版で修正してみました。
お試しいただければ幸いです。

http://nanno.dip.jp/softlib/rlogin/2.26.1/

**Comment by webspsuzuki** [comment]
試作版で確認しました。想定どおりの動作になっていました。
早々のご対応誠にありがとうございました。
