### ISSUE TITLE
[BUG]複数接続時かつ画面スクロール中のCTRL-Cによる停止時間

### ISSUE THREAD

**Issue by archvile** [kmiya-culti/RLogin#7]
# バージョン
・CentOS7,6,5 /Debian 8
・Windows10 x64
・RLogin 2.22.8

# 再現手順
1. SSH接続で複数タブを開く
2. cat /var/log/messages 等で大き目のファイルを端末に表示させる
3. 表示してスクロールしている最中にctrl-cを入力し出力を停止させる。

# 内容
・CTRL-Cを入力後、サーバーへ送信されるまでの応答時間がローカルのサーバーへの接続でも反応するまでに時間がかかります。
・CTRL-Cを入力後、タブを切り替える操作を行うと、そのタイミングでctrl-cが入力されるようで再度タブを入力したタブへ戻すと停止しています。
・接続数が1の場合は多少反応するまでに時間がかかりますが、実用上は問題ない応答です。

**Comment by kmiya-culti** [comment]
受信バッファと送信のタイミングの問題のようですね。
CTRL+C以外でもCTRL+S(XOFF)CTRL+Q(XON)でも同様にタイミングが合いません。

受信バッファのサイズを小さくすると改善されると思うのですが、全体的に表示が遅く感じることが
あるので難しいところです。（ZModemなどのファイル転送が遅くなることがあります）

通信速度との兼ね合いで良い値を算出できないか考えてみたいと思います。
ご意見、有り難うございました。

**Comment by kmiya-culti** [comment]
2.22.9からssh2の場合は、バッファサイズを指定できるようにして効果があるようでした。
rlogin/telnetの場合は、バッファサイズを変更してもほとんど効果がありませんでしたので設定を追加しませんでした。
