### ISSUE TITLE
自動バージョンチェックが動作していないようです

### ISSUE THREAD

**Issue by webspsuzuki** [kmiya-culti/RLogin#72]
自動バージョンチェックが正常動作していないと思われます。
nanno.dip.jp にアクセスできないようです。

お使いのDDNSに係る問題かと思いますが、一度ご確認の程お願い致します。

**Comment by kmiya-culti** [comment]
お察しのように現在dip.jpのDDNSの更新が停止されている為にnanno.dip.jpにアクセスできない状態が続いているようです。
しかしバージョン2.26.0からnanno.dip.jpにアクセス出来ない場合にGitHubでチェックするように変更してあります。

**Comment by webspsuzuki** [comment]
既に対処済みとの事で、大変失礼しました。
バージョン2.25.8で確認していました。
ありがとうございます。
