### ISSUE TITLE
jpeg表示について

### ISSUE THREAD

**Issue by nopnop2002** [kmiya-culti/RLogin#73]
まずは素晴らしいソフトの提供、ありがとうございます。
Rloginを使用すればjpeg画像を表示できると聞いて試してみましたが、表示できません。
何が問題なのか教えて頂ければ嬉しいです。

- 使用しているバージョン
![RloginVersion](https://user-images.githubusercontent.com/6020549/120098410-c1643580-c170-11eb-8998-68ee1f8246b0.jpg)

- ログインの設定
![RloginConnection](https://user-images.githubusercontent.com/6020549/120098418-cb863400-c170-11eb-84bd-73767c92e814.jpg)

- コマンド実行結果(先頭部分のみ抜粋)
![RloginJpeg](https://user-images.githubusercontent.com/6020549/120098464-1607b080-c171-11eb-9dc8-b68929c17cbb.jpg)

よろしくお願いします。

**Comment by kmiya-culti** [comment]
Netpbmですね・・・懐かしいです。
ppmtosixelは、C1制御文字のDCS($90)を使用しますが
https://kmiya-culti.github.io/RLogin/#TERMOPT
の「?8454 C1制御文字を無視する」がデフォルトONで無視するようにしています。

これは・・・
https://kmiya-culti.github.io/RLogin/faq.html#C1ABORT
が再々にわたってバグ報告されるのでONにした経緯があります

制御コードのオプション設定?8454のチェックを外して
「?8454 C1制御文字を処理する」にしてみてください。

**Comment by nopnop2002** [comment]
素早いレスポンス、ありがとうございます。

>制御コードのオプション設定?8454のチェックを外して

問題なく表示されました。

![8454_on](https://user-images.githubusercontent.com/6020549/120102919-355e0800-c188-11eb-9f5b-68690cd44916.jpg)


すいません。ついでと言っては誠に申し訳ないのですが、
```
jpegtopnm esp32.jpeg  | pnmquant 256 | ppmtosixel
```
は推奨されないコマンドなのでしょうか？？
デフォルトでJPEGを表示することが出来るコマンドが有れば教えてください。

よろしくお願いします。

**Comment by kmiya-culti** [comment]
色々あると思いますが・・・
https://kmiya-culti.github.io/RLogin/#REGWIND
に記載しているlibsixelがお薦めでしょうか
https://github.com/saitoha/libsixel

arakikenさんが書かれたsixelについて一読するのも面白いかもしれません
https://qiita.com/arakiken/items/4a216af6547d2574d283
https://qiita.com/arakiken/items/3e4bc9a6e43af0198e46

また、動作が違いますがiTerm2のInline Images Protocolにも対応しているので
https://iterm2.com/documentation-images.html
のimgcatなどでも画像を表示できます

**Comment by nopnop2002** [comment]
おはようございます。

img2sixelを使えば、制御コードのオプション設定?8454のチェックを外さなくてもイメージが表示されました。

お時間が有るときに、https://kmiya-culti.github.io/RLogin/　の4.2章の以下の記述を変更して頂けると
助かります。

```
Netpbmなどのコンバーターを使用すれば画像が表示されます
jpegtopnm tiger.jpg | pnmquant 256 | ppmtosixel
```

これを見た人はまずはこのコマンドを試すと思います。
ありがとうございました。
