### ISSUE TITLE
【問合せ】RLoginの配布サイト「 http://nanno.dip.jp/softlib/man/rlogin/ 」がアクセス不能状態が続いています

### ISSUE THREAD

**Issue by ryosan-5608** [kmiya-culti/RLogin#75]
ここしばらく、RLoginの（メイン？）配布サイト「 http://nanno.dip.jp/softlib/man/rlogin/ 」にアクセス出来ない状態が続いていますが、どういった状況でしょうか？

現状、RLoginの（サブ？）配布サイト「 https://kmiya-culti.github.io/RLogin/ 」が健在なので、RLoginのダウンロードに支障はありません。

しかしながら、「 http://nanno.dip.jp/softlib/man/rlogin/ 」のダウンが続くと、こんなデメリットがあると思います。

・「 https://kmiya-culti.github.io/RLogin/ 」サイト内のリンク先が一部「 http://nanno.dip.jp/ 」配下のURLのままであるため、リンク切れ状態となっています

・他WebサイトでRLoginの紹介記事がよくありますが、公式配布サイトとして「 http://nanno.dip.jp/softlib/man/rlogin/ 」が紹介されていることが多いため、Google検索等で「 https://kmiya-culti.github.io/RLogin/ 」の存在を察知出来なければRLoginのダウンロードが出来なくなります

・初めてRLoginを使おうとしている人にとって、Google検索等で「 https://kmiya-culti.github.io/RLogin/ 」がヒットしても、本当に作者のサイトかどうか疑問に思う（偽の（コンピュータウイルス入り）配布サイトかもしれない？）可能性があります

差し当たっての大きな支障はありませんが、気になったので質問させて頂きました。

**Comment by kmiya-culti** [comment]
現在dip.jpのDDNSが停止されている為にnanno.dip.jpにアクセス出来ない状態が続いています。
https://twitter.com/agorainc
