### ISSUE TITLE
[BUG]メニューを開いている間ポートフォワードが止まる

### ISSUE THREAD

**Issue by slotport** [kmiya-culti/RLogin#8]
# バージョン
- Windows 10 x64
- RLogin 2.22.9b
- ログイン先 CentOS7

# 再現手順
1. ローカルのWindowsからRLoginでリモートのCentOS (host A)にSSH接続する  
    このとき、ポート転送を有効にしておく。
2. 1で転送したポートで接続する。  
    例として、フォワードしたポートでリモートのhost BにSSH接続する。
3. 2のセッションで `ping 127.0.0.1` のように定期的に出力のあるコマンドを実行しておく
4. ローカルの(ポート転送している)RLoginで右クリックして、コンテキストメニューを開く
5. `ping 127.0.0.1`の表示が止まる。

# 内容
メニューを開いている間、ポート転送のパケットが止まっているように見えます。
コンテキストメニューではなく、メニューバーの「ファイル(F)」等だと、
完全に止まりはしませんが、遅くなります。

**Comment by kmiya-culti** [comment]
基本メニュー操作中は、アイドリング処理されませんのでそのような動作になります。
なにか良い処理方法を考えてみようと思います。
ご意見有り難うございました。

**Comment by kmiya-culti** [comment]
2.22.9からメニュー操作中にタイマーで処理するようにしました。
メインのポップアップメニューでも同じように処理してみましたが、問題がありました。
ポップアップメニュー表示中に接続がクロースされるとハングアップするタイミングがあります。

次回バージョンでは、タブのドラッグ時、すべてのポップアップメニューでもアイドリング処理を実行するように変更しようと思います。

**Comment by slotport** [comment]
ありがとうございます！
