### ISSUE TITLE
mDNS(*.local)ホスト名への接続に20秒以上かかる

### ISSUE THREAD

**Issue by mono1729** [kmiya-culti/RLogin#85]
同一LAN上のSSHホストに接続するために .local のホスト名を指定すると、
接続まで20秒以上かかり、その間RLoginの応答が長時間なくなります。
同一環境にてWindows標準のopensshでは3秒ほどで接続できます。

半年程前は起きていなかった覚えがありますが、1年以上前のRLoginに戻しても現象は再現しました。
Windows側で何か変更があり発生しているのかもしれません。

再現環境
RLoginバージョン: 2.26.5 (2021/11/29)
接続元OS: Windows 10 20H2
接続先OS: Ubuntu 20.04, FreeBSD 13

**Comment by kmiya-culti** [comment]
関係ありそうなオプション・プロトコルの「DNSでホスト鍵をチェックしない」をチェックしてみてください
応答が停止するようなロック状態が改善するかもしれません。

動作を確認したら最近のWindowsでは、DNSでSSHFPが機能しないようです。次回バージョンからこのオプションの意味を反転して「チェックする」にしようと思います。
