### ISSUE TITLE
[BUG]複数タブに対して「すべての状態を保存」実行時の並び順について

### ISSUE THREAD

**Issue by archvile** [kmiya-culti/RLogin#9]
# バージョン
- CentOS7,6,5
- Debian 8
- Windows10 x64
- RLogin 2.22.9/2.22.8

# 再現手順
- SSHの接続を複数サーバーに対して同時に接続し、タブ列の並びを好みの順に並べる。
- ファイル->すべての状態を保存を実行し、名前を付けて保存しておく。
- 実行ファイルのショートカットを作成、編集し、保存したrlgファイルを引数に指定し、ショートカットを実行する。
- もしくはrlgファイルをRLoginに関連付けしておいて直接実行する。

# 内容
- 「すべての状態を保存」(ID_FILE_ALL_SAVE)のコマンドによる保存の際にタブの並び順が正確に保存されません。
- rlgファイルを読み取り後、タブの並びを変更せずに再度保存すると同様の現象になりランダムに位置が変わります。
- タブが複製されて保存され、オープン時に同一サーバーに別タブで2回接続される。
気が付くと複製されているようなので厳密な検証はできていません。(気のせい？)
- rlgファイルを開いて、閉じて、再度開く際に意図通りでは無いながら並び順は再現していますので、読み取りは問題ないように見えます。

**Comment by kmiya-culti** [comment]
タブの並び順については、まったく考慮していませんでした・・・接続された順番で並びますね。
タブの順位も保存するように考えてみます。
ご意見有り難うございました。

**Comment by kmiya-culti** [comment]
2.23.0からタブバーの位置も保存・復元するように変更しました。
