### ISSUE TITLE
プロトコルハンドラ機能からRLoginを起動した場合、エントリースクリプトが正常に動作しないバグ

### ISSUE THREAD

**Issue by kiyofumi-oba** [kmiya-culti/RLogin#90]
Rlogin、これ無しでは仕事にならないくらい、いつも使わせていただいております。

私はプロトコルハンドラ機能を使って、接続先をhtmlファイルで管理しているのですが、
プロトコルハンドラ機能からRloginを起動した場合、エントリースクリプトが正常に動作しないバグを確認しました。

確認version：2.26.9
動作OS：Windows10

具体的には、エントリースクリプトを以下の記事にあるように設定して、

>RLoginスクリプトをキーボードショートカットで実行 - Qiita
>https://qiita.com/mitazet/items/bd4d46e19a142bf09094

ショートカットキーを押下することでスクリプトを実行できるようにし、便利に使っていたのですが、
これがどこかのバージョンから、プロトコルハンドラ機能でRLoginを起動させた場合、
includeで呼び出したスクリプトファイルが読み込まれずに、ショートカットキーを押すと実行エラーとなる、
という現象です。
（※エントリースクリプト自体は実行されているのでメニューに表示はされます）

Rloginをexeから起動した場合は、上記の現状は起きません。

プロトコルハンドラ機能を重宝しておりますので、ぜひ今後修正のご対応いただければと思います。

**Comment by kmiya-culti** [comment]
カレントディレクトリが違う為、そのような動作になると思います。
スクリプト内でchdir するか絶対パスでファイルを指定すれば良いと思います。

**Comment by kiyofumi-oba** [comment]
絶対パスで動きました。
よくよく考えればすぐ思いつきそうな内容でしたね……。
お手数おかけしましたが、ありがとうございました。
