### ISSUE TITLE
[要望]「SSH鍵ファイルの読み込み」ダイアログのフォーカス

### ISSUE THREAD

**Issue by Takumiboo** [kmiya-culti/RLogin#92]
いつもありがたく使わせていただいております。

SSH認証鍵ファイルを事前に設定しておくと、接続する際にパスフレーズのプロンプトが出ますが、
その際のデフォルトのフォーカスが鍵ファイル欄になっていて、パスフレーズ入力欄にフォーカスを移動する必要があります。

SSH認証鍵ファイルがすでに入力されている状態であれば、デフォルトのフォーカスがパスフレーズ入力欄になっていると、そのままパスフレーズが入力できるため、より便利になるかと思います。

ご検討のほどよろしくお願いします。

**Comment by kmiya-culti** [comment]
次回バージョンで変更しようと思います。
お試しいただければ幸いです。

http://nanno.bf1.jp/softlib/rlogin/2.27.2/

**Comment by Takumiboo** [comment]
早速のご対応ありがとうございます！
確認させていただき、要望通り実装されていることを確認しました。
お忙しい中ご対応いただきありがとうございました！
