### ISSUE TITLE
接続設定が多いと起動・終了が遅い

### ISSUE THREAD

**Issue by a573net** [kmiya-culti/RLogin#93]
いつも便利に利用させて頂いております。仕事で利用させて頂いており、便利すぎて、もうteratermには戻れません。朝起動して夕方帰るまで、毎日常駐です。

300近い接続設定を設定していると、起動・終了が遅いと感じています。

ウインドウが止まっている感じなので、何かのタイムアウトを待っている感じです。
パスワードロックを掛けています。パスワード入力後に、接続一覧が表示されるまで約25秒かかります。
INIファイルで運用していますが、こちらが遅くなる原因なのでしょうか・・・
プロセス間通信を待っているのでしょうか・・・

接続設定が多すぎと言われるとそれまでですが、お手すきのタイミングで改善頂けると非常に助かります。

**Comment by kmiya-culti** [comment]
基本プライベートプロファイルは、非常に動作が遅いです。
次回バージョンで少しでも改善するように一部の項目を圧縮するようにしてサイズを小さくするように変更してみました。
お試しいただければ幸いです。

http://nanno.bf1.jp/softlib/rlogin/2.27.2/

**Comment by a573net** [comment]
早々にご対応ありがとうございます。
25秒が13秒に短縮しました。
ありがとうございました。
これからもガッツリ使わせて頂きます！

**Comment by inopar** [comment]
会社の開発環境がレジストリ保存が出来ない関係でINIファイル運用をしておりました。
同じく起動・終了に時間がかかっておりましたが、20秒から6秒前後になり大変助かりました！
これからも使わせて頂きます！
