### ISSUE TITLE
スクリプトでの配列とforeach()の問題

### ISSUE THREAD

**Issue by miffy** [kmiya-culti/RLogin#94]
いつもお世話になっております。
先日は改修していただき、スクリプトの実行が楽になり、大変ありがとうございました。

今回もスクリプトの不具合です。
配列とforeach()を使うと問題があります。

version 2.27.1

元々、サンプルコードが少なくて試行錯誤でやっているので、
文法の問題かもしれませんが、要素4以下の配列で以下のようなエラーが出ます。
Script Error 'CScriptValue Null int'

サンプルコード
```
users = ["test1", "test2", "test3", "test4"];

foreach ( val in users ){
  sputs(sprintf("ls -la /home/%s/\n", val));
}
```

以下のように、一つ一つ入れる方法では

```
users[] = "test1";
users[] = "test2";
users[] = "test3";
```
3要素以上だとエラーが出ません（2以下だと不具合が出る）。
たくさん要素がある配列を使えばいいのですが、初めは少数の配列でテストしているので厳しいです。

**Comment by kmiya-culti** [comment]
確認出来ました。次回バージョンで修正いたします。
ご報告有り難うございました。

http://nanno.bf1.jp/softlib/rlogin/2.27.2/

**Comment by miffy** [comment]
ご対応ありがとうございます。
更に仕事がはかどりそうです。
