### ISSUE TITLE
ローカルエディットモードでクラッシュ

### ISSUE THREAD

**Issue by bata24** [kmiya-culti/RLogin#97]
バージョン2.27.5です。

オプション→サーバー→通信共通→「キーボード入力をローカルエディットモードにする」にチェックを入れた状態で、
VMware上で動かしているUbuntu22.04にログインし、vimで適当なファイルを編集すると、バックスペースやEscなどのキーを押したタイミングでプログラムがクラッシュします。

オプションを色々試していたところ、上記挙動を発見したので報告致します。

**Comment by kmiya-culti** [comment]
基本的にローカルエディットモードは、PipeやCOMなどでキー入力が編集・エコーバックされない場合を想定しています。
viなどキー編集動作とは、非常に相性が悪いので注意が必要です

あまりにも放置していた機能なので内部動作を見直しショートカットやコントロールコードの編集などを変更しメニューで有効・無効が出来るようにしました。
http://nanno.bf1.jp/softlib/rlogin/2.27.7/
